//package molecule.core.dsl
//
//import molecule.core.composition.CompositeInit_0._
//import molecule.core.composition.CompositeInit_1._
//import molecule.core.composition.CompositeInit_2._
//import molecule.core.composition.CompositeInit_3._
//import molecule.core.composition.Tx._
//import scala.language.higherKinds
//
//// Build on from entity id
////      def apply(e: Long): In1_0[obj, props, I1] = ???
//// Build on from entity id
////      def apply(e: Long): In2_0[obj, props, I1, I2] = ???
//
//// Build on from entity id
////      def apply(e: Long): In3_0[obj, props, I1, I2, I3] = ???
//
///** Type distribution to groups of functionality. */
//object composite_tx {
//
//  trait CompTx_0_00[obj[_], props                                                                  ] extends CompositeInit_0_00[obj, props                                                                  ] with Tx00[obj, props                                                                  ]
//  trait CompTx_0_01[obj[_], props, A                                                               ] extends CompositeInit_0_01[obj, props, A                                                               ] with Tx01[obj, props, A                                                               ]
//  trait CompTx_0_02[obj[_], props, A, B                                                            ] extends CompositeInit_0_02[obj, props, A, B                                                            ] with Tx02[obj, props, A, B                                                            ]
//  trait CompTx_0_03[obj[_], props, A, B, C                                                         ] extends CompositeInit_0_03[obj, props, A, B, C                                                         ] with Tx03[obj, props, A, B, C                                                         ]
//  trait CompTx_0_04[obj[_], props, A, B, C, D                                                      ] extends CompositeInit_0_04[obj, props, A, B, C, D                                                      ] with Tx04[obj, props, A, B, C, D                                                      ]
//  trait CompTx_0_05[obj[_], props, A, B, C, D, E                                                   ] extends CompositeInit_0_05[obj, props, A, B, C, D, E                                                   ] with Tx05[obj, props, A, B, C, D, E                                                   ]
//  trait CompTx_0_06[obj[_], props, A, B, C, D, E, F                                                ] extends CompositeInit_0_06[obj, props, A, B, C, D, E, F                                                ] with Tx06[obj, props, A, B, C, D, E, F                                                ]
//  trait CompTx_0_07[obj[_], props, A, B, C, D, E, F, G                                             ] extends CompositeInit_0_07[obj, props, A, B, C, D, E, F, G                                             ] with Tx07[obj, props, A, B, C, D, E, F, G                                             ]
//  trait CompTx_0_08[obj[_], props, A, B, C, D, E, F, G, H                                          ] extends CompositeInit_0_08[obj, props, A, B, C, D, E, F, G, H                                          ] with Tx08[obj, props, A, B, C, D, E, F, G, H                                          ]
//  trait CompTx_0_09[obj[_], props, A, B, C, D, E, F, G, H, I                                       ] extends CompositeInit_0_09[obj, props, A, B, C, D, E, F, G, H, I                                       ] with Tx09[obj, props, A, B, C, D, E, F, G, H, I                                       ]
//  trait CompTx_0_10[obj[_], props, A, B, C, D, E, F, G, H, I, J                                    ] extends CompositeInit_0_10[obj, props, A, B, C, D, E, F, G, H, I, J                                    ] with Tx10[obj, props, A, B, C, D, E, F, G, H, I, J                                    ]
//  trait CompTx_0_11[obj[_], props, A, B, C, D, E, F, G, H, I, J, K                                 ] extends CompositeInit_0_11[obj, props, A, B, C, D, E, F, G, H, I, J, K                                 ] with Tx11[obj, props, A, B, C, D, E, F, G, H, I, J, K                                 ]
//  trait CompTx_0_12[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L                              ] extends CompositeInit_0_12[obj, props, A, B, C, D, E, F, G, H, I, J, K, L                              ] with Tx12[obj, props, A, B, C, D, E, F, G, H, I, J, K, L                              ]
//  trait CompTx_0_13[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] extends CompositeInit_0_13[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] with Tx13[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ]
//  trait CompTx_0_14[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] extends CompositeInit_0_14[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] with Tx14[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ]
//  trait CompTx_0_15[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] extends CompositeInit_0_15[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] with Tx15[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ]
//  trait CompTx_0_16[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] extends CompositeInit_0_16[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] with Tx16[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ]
//  trait CompTx_0_17[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] extends CompositeInit_0_17[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] with Tx17[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ]
//  trait CompTx_0_18[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] extends CompositeInit_0_18[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] with Tx18[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ]
//  trait CompTx_0_19[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] extends CompositeInit_0_19[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] with Tx19[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ]
//  trait CompTx_0_20[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] extends CompositeInit_0_20[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] with Tx20[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ]
//  trait CompTx_0_21[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] extends CompositeInit_0_21[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] with Tx21[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ]
//  trait CompTx_0_22[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends CompositeInit_0_22[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] with Tx22[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
//
//  trait CompTx_1_00[obj[_], props, I1                                                                  ] extends CompositeInit_1_00[obj, props, I1                                                                  ] with Tx00[obj, props                                                                  ]
//  trait CompTx_1_01[obj[_], props, I1, A                                                               ] extends CompositeInit_1_01[obj, props, I1, A                                                               ] with Tx01[obj, props, A                                                               ]
//  trait CompTx_1_02[obj[_], props, I1, A, B                                                            ] extends CompositeInit_1_02[obj, props, I1, A, B                                                            ] with Tx02[obj, props, A, B                                                            ]
//  trait CompTx_1_03[obj[_], props, I1, A, B, C                                                         ] extends CompositeInit_1_03[obj, props, I1, A, B, C                                                         ] with Tx03[obj, props, A, B, C                                                         ]
//  trait CompTx_1_04[obj[_], props, I1, A, B, C, D                                                      ] extends CompositeInit_1_04[obj, props, I1, A, B, C, D                                                      ] with Tx04[obj, props, A, B, C, D                                                      ]
//  trait CompTx_1_05[obj[_], props, I1, A, B, C, D, E                                                   ] extends CompositeInit_1_05[obj, props, I1, A, B, C, D, E                                                   ] with Tx05[obj, props, A, B, C, D, E                                                   ]
//  trait CompTx_1_06[obj[_], props, I1, A, B, C, D, E, F                                                ] extends CompositeInit_1_06[obj, props, I1, A, B, C, D, E, F                                                ] with Tx06[obj, props, A, B, C, D, E, F                                                ]
//  trait CompTx_1_07[obj[_], props, I1, A, B, C, D, E, F, G                                             ] extends CompositeInit_1_07[obj, props, I1, A, B, C, D, E, F, G                                             ] with Tx07[obj, props, A, B, C, D, E, F, G                                             ]
//  trait CompTx_1_08[obj[_], props, I1, A, B, C, D, E, F, G, H                                          ] extends CompositeInit_1_08[obj, props, I1, A, B, C, D, E, F, G, H                                          ] with Tx08[obj, props, A, B, C, D, E, F, G, H                                          ]
//  trait CompTx_1_09[obj[_], props, I1, A, B, C, D, E, F, G, H, I                                       ] extends CompositeInit_1_09[obj, props, I1, A, B, C, D, E, F, G, H, I                                       ] with Tx09[obj, props, A, B, C, D, E, F, G, H, I                                       ]
//  trait CompTx_1_10[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J                                    ] extends CompositeInit_1_10[obj, props, I1, A, B, C, D, E, F, G, H, I, J                                    ] with Tx10[obj, props, A, B, C, D, E, F, G, H, I, J                                    ]
//  trait CompTx_1_11[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K                                 ] extends CompositeInit_1_11[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K                                 ] with Tx11[obj, props, A, B, C, D, E, F, G, H, I, J, K                                 ]
//  trait CompTx_1_12[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L                              ] extends CompositeInit_1_12[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L                              ] with Tx12[obj, props, A, B, C, D, E, F, G, H, I, J, K, L                              ]
//  trait CompTx_1_13[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] extends CompositeInit_1_13[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] with Tx13[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ]
//  trait CompTx_1_14[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] extends CompositeInit_1_14[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] with Tx14[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ]
//  trait CompTx_1_15[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] extends CompositeInit_1_15[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] with Tx15[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ]
//  trait CompTx_1_16[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] extends CompositeInit_1_16[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] with Tx16[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ]
//  trait CompTx_1_17[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] extends CompositeInit_1_17[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] with Tx17[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ]
//  trait CompTx_1_18[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] extends CompositeInit_1_18[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] with Tx18[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ]
//  trait CompTx_1_19[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] extends CompositeInit_1_19[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] with Tx19[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ]
//  trait CompTx_1_20[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] extends CompositeInit_1_20[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] with Tx20[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ]
//  trait CompTx_1_21[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] extends CompositeInit_1_21[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] with Tx21[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ]
//  trait CompTx_1_22[obj[_], props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends CompositeInit_1_22[obj, props, I1, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] with Tx22[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
//
//  trait CompTx_2_00[obj[_], props, I1, I2                                                                  ] extends CompositeInit_2_00[obj, props, I1, I2                                                                  ] with Tx00[obj, props                                                                  ]
//  trait CompTx_2_01[obj[_], props, I1, I2, A                                                               ] extends CompositeInit_2_01[obj, props, I1, I2, A                                                               ] with Tx01[obj, props, A                                                               ]
//  trait CompTx_2_02[obj[_], props, I1, I2, A, B                                                            ] extends CompositeInit_2_02[obj, props, I1, I2, A, B                                                            ] with Tx02[obj, props, A, B                                                            ]
//  trait CompTx_2_03[obj[_], props, I1, I2, A, B, C                                                         ] extends CompositeInit_2_03[obj, props, I1, I2, A, B, C                                                         ] with Tx03[obj, props, A, B, C                                                         ]
//  trait CompTx_2_04[obj[_], props, I1, I2, A, B, C, D                                                      ] extends CompositeInit_2_04[obj, props, I1, I2, A, B, C, D                                                      ] with Tx04[obj, props, A, B, C, D                                                      ]
//  trait CompTx_2_05[obj[_], props, I1, I2, A, B, C, D, E                                                   ] extends CompositeInit_2_05[obj, props, I1, I2, A, B, C, D, E                                                   ] with Tx05[obj, props, A, B, C, D, E                                                   ]
//  trait CompTx_2_06[obj[_], props, I1, I2, A, B, C, D, E, F                                                ] extends CompositeInit_2_06[obj, props, I1, I2, A, B, C, D, E, F                                                ] with Tx06[obj, props, A, B, C, D, E, F                                                ]
//  trait CompTx_2_07[obj[_], props, I1, I2, A, B, C, D, E, F, G                                             ] extends CompositeInit_2_07[obj, props, I1, I2, A, B, C, D, E, F, G                                             ] with Tx07[obj, props, A, B, C, D, E, F, G                                             ]
//  trait CompTx_2_08[obj[_], props, I1, I2, A, B, C, D, E, F, G, H                                          ] extends CompositeInit_2_08[obj, props, I1, I2, A, B, C, D, E, F, G, H                                          ] with Tx08[obj, props, A, B, C, D, E, F, G, H                                          ]
//  trait CompTx_2_09[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I                                       ] extends CompositeInit_2_09[obj, props, I1, I2, A, B, C, D, E, F, G, H, I                                       ] with Tx09[obj, props, A, B, C, D, E, F, G, H, I                                       ]
//  trait CompTx_2_10[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J                                    ] extends CompositeInit_2_10[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J                                    ] with Tx10[obj, props, A, B, C, D, E, F, G, H, I, J                                    ]
//  trait CompTx_2_11[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K                                 ] extends CompositeInit_2_11[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K                                 ] with Tx11[obj, props, A, B, C, D, E, F, G, H, I, J, K                                 ]
//  trait CompTx_2_12[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L                              ] extends CompositeInit_2_12[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L                              ] with Tx12[obj, props, A, B, C, D, E, F, G, H, I, J, K, L                              ]
//  trait CompTx_2_13[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] extends CompositeInit_2_13[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] with Tx13[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ]
//  trait CompTx_2_14[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] extends CompositeInit_2_14[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] with Tx14[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ]
//  trait CompTx_2_15[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] extends CompositeInit_2_15[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] with Tx15[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ]
//  trait CompTx_2_16[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] extends CompositeInit_2_16[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] with Tx16[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ]
//  trait CompTx_2_17[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] extends CompositeInit_2_17[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] with Tx17[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ]
//  trait CompTx_2_18[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] extends CompositeInit_2_18[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] with Tx18[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ]
//  trait CompTx_2_19[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] extends CompositeInit_2_19[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] with Tx19[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ]
//  trait CompTx_2_20[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] extends CompositeInit_2_20[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] with Tx20[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ]
//  trait CompTx_2_21[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] extends CompositeInit_2_21[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] with Tx21[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ]
//  trait CompTx_2_22[obj[_], props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends CompositeInit_2_22[obj, props, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] with Tx22[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
//
//  trait CompTx_3_00[obj[_], props, I1, I2, I3                                                                  ] extends CompositeInit_3_00[obj, props, I1, I2, I3                                                                  ] with Tx00[obj, props                                                                  ]
//  trait CompTx_3_01[obj[_], props, I1, I2, I3, A                                                               ] extends CompositeInit_3_01[obj, props, I1, I2, I3, A                                                               ] with Tx01[obj, props, A                                                               ]
//  trait CompTx_3_02[obj[_], props, I1, I2, I3, A, B                                                            ] extends CompositeInit_3_02[obj, props, I1, I2, I3, A, B                                                            ] with Tx02[obj, props, A, B                                                            ]
//  trait CompTx_3_03[obj[_], props, I1, I2, I3, A, B, C                                                         ] extends CompositeInit_3_03[obj, props, I1, I2, I3, A, B, C                                                         ] with Tx03[obj, props, A, B, C                                                         ]
//  trait CompTx_3_04[obj[_], props, I1, I2, I3, A, B, C, D                                                      ] extends CompositeInit_3_04[obj, props, I1, I2, I3, A, B, C, D                                                      ] with Tx04[obj, props, A, B, C, D                                                      ]
//  trait CompTx_3_05[obj[_], props, I1, I2, I3, A, B, C, D, E                                                   ] extends CompositeInit_3_05[obj, props, I1, I2, I3, A, B, C, D, E                                                   ] with Tx05[obj, props, A, B, C, D, E                                                   ]
//  trait CompTx_3_06[obj[_], props, I1, I2, I3, A, B, C, D, E, F                                                ] extends CompositeInit_3_06[obj, props, I1, I2, I3, A, B, C, D, E, F                                                ] with Tx06[obj, props, A, B, C, D, E, F                                                ]
//  trait CompTx_3_07[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G                                             ] extends CompositeInit_3_07[obj, props, I1, I2, I3, A, B, C, D, E, F, G                                             ] with Tx07[obj, props, A, B, C, D, E, F, G                                             ]
//  trait CompTx_3_08[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H                                          ] extends CompositeInit_3_08[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H                                          ] with Tx08[obj, props, A, B, C, D, E, F, G, H                                          ]
//  trait CompTx_3_09[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I                                       ] extends CompositeInit_3_09[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I                                       ] with Tx09[obj, props, A, B, C, D, E, F, G, H, I                                       ]
//  trait CompTx_3_10[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J                                    ] extends CompositeInit_3_10[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J                                    ] with Tx10[obj, props, A, B, C, D, E, F, G, H, I, J                                    ]
//  trait CompTx_3_11[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K                                 ] extends CompositeInit_3_11[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K                                 ] with Tx11[obj, props, A, B, C, D, E, F, G, H, I, J, K                                 ]
//  trait CompTx_3_12[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L                              ] extends CompositeInit_3_12[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L                              ] with Tx12[obj, props, A, B, C, D, E, F, G, H, I, J, K, L                              ]
//  trait CompTx_3_13[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] extends CompositeInit_3_13[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] with Tx13[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M                           ]
//  trait CompTx_3_14[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] extends CompositeInit_3_14[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] with Tx14[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ]
//  trait CompTx_3_15[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] extends CompositeInit_3_15[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] with Tx15[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ]
//  trait CompTx_3_16[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] extends CompositeInit_3_16[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] with Tx16[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ]
//  trait CompTx_3_17[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] extends CompositeInit_3_17[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] with Tx17[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ]
//  trait CompTx_3_18[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] extends CompositeInit_3_18[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] with Tx18[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ]
//  trait CompTx_3_19[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] extends CompositeInit_3_19[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] with Tx19[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ]
//  trait CompTx_3_20[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] extends CompositeInit_3_20[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] with Tx20[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ]
//  trait CompTx_3_21[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] extends CompositeInit_3_21[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] with Tx21[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ]
//  trait CompTx_3_22[obj[_], props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends CompositeInit_3_22[obj, props, I1, I2, I3, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] with Tx22[obj, props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
//}