package molecule.core.marshalling.unpack

import molecule.core.ops.TreeOps
import scala.reflect.macros.blackbox

trait Unpackers extends TreeOps with UnpackTypes {
  val c: blackbox.Context

  import c.universe._

  def unpackLambdas(v: Tree): Array[Tree] = Array(
    /*   0 */ q"unpackOneString($v, vs)",
    /*   1 */ q"unpackOneInt($v)",
    /*   2 */ q"unpackOneInt($v)", // (slot for int2 cast)
    /*   3 */ q"unpackOneLong($v)",
    /*   4 */ q"unpackOneDouble($v)",
    /*   5 */ q"unpackOneBoolean($v)",
    /*   6 */ q"unpackOneDate($v)",
    /*   7 */ q"unpackOneUUID($v)",
    /*   8 */ q"unpackOneURI($v)",
    /*   9 */ q"unpackOneBigInt($v)",
    /*  10 */ q"unpackOneBigDecimal($v)",
    /*  11 */ q"unpackOneAny($v)",
    /*  12 */ q"unpackOptOneEnum($v)",
    /*  13 */ q"unpackOptOneString($v, vs)",
    /*  14 */ q"unpackOptOneInt($v)",
    /*  15 */ q"unpackOptOneLong($v)",
    /*  16 */ q"unpackOptOneDouble($v)",
    /*  17 */ q"unpackOptOneBoolean($v)",
    /*  18 */ q"unpackOptOneDate($v)",
    /*  19 */ q"unpackOptOneUUID($v)",
    /*  20 */ q"unpackOptOneURI($v)",
    /*  21 */ q"unpackOptOneBigInt($v)",
    /*  22 */ q"unpackOptOneBigDecimal($v)",
    /*  23 */ q"unpackOptOneRefAttr($v)",
    /*  24 */ q"unpackManyEnum($v)",
    /*  25 */ q"unpackManyString($v, vs)",
    /*  26 */ q"unpackManyInt($v)",
    /*  27 */ q"unpackManyLong($v)",
    /*  28 */ q"unpackManyDouble($v)",
    /*  29 */ q"unpackManyBoolean($v)",
    /*  30 */ q"unpackManyDate($v)",
    /*  31 */ q"unpackManyUUID($v)",
    /*  32 */ q"unpackManyURI($v)",
    /*  33 */ q"unpackManyBigInt($v)",
    /*  34 */ q"unpackManyBigDecimal($v)",
    /*  35 */ q"unpackOptManyEnum($v)",
    /*  36 */ q"unpackOptManyString($v, vs)",
    /*  37 */ q"unpackOptManyInt($v)",
    /*  38 */ q"unpackOptManyLong($v)",
    /*  39 */ q"unpackOptManyDouble($v)",
    /*  40 */ q"unpackOptManyBoolean($v)",
    /*  41 */ q"unpackOptManyDate($v)",
    /*  42 */ q"unpackOptManyUUID($v)",
    /*  43 */ q"unpackOptManyURI($v)",
    /*  44 */ q"unpackOptManyBigInt($v)",
    /*  45 */ q"unpackOptManyBigDecimal($v)",
    /*  46 */ q"unpackOptManyRefAttr($v)",
    /*  47 */ q"unpackMapString($v, vs)",
    /*  48 */ q"unpackMapInt($v)",
    /*  49 */ q"unpackMapLong($v)",
    /*  50 */ q"unpackMapDouble($v)",
    /*  51 */ q"unpackMapBoolean($v)",
    /*  52 */ q"unpackMapDate($v)",
    /*  53 */ q"unpackMapUUID($v)",
    /*  54 */ q"unpackMapURI($v)",
    /*  55 */ q"unpackMapBigInt($v)",
    /*  56 */ q"unpackMapBigDecimal($v)",
    /*  57 */ q"unpackOptMapString($v, vs)",
    /*  58 */ q"unpackOptMapInt($v)",
    /*  59 */ q"unpackOptMapLong($v)",
    /*  60 */ q"unpackOptMapDouble($v)",
    /*  61 */ q"unpackOptMapBoolean($v)",
    /*  62 */ q"unpackOptMapDate($v)",
    /*  63 */ q"unpackOptMapUUID($v)",
    /*  64 */ q"unpackOptMapURI($v)",
    /*  65 */ q"unpackOptMapBigInt($v)",
    /*  66 */ q"unpackOptMapBigDecimal($v)",
    /*  67 */ q"unpackOptApplyOneString($v, vs)",
    /*  68 */ q"unpackOptApplyOneInt($v)",
    /*  69 */ q"unpackOptApplyOneLong($v)",
    /*  70 */ q"unpackOptApplyOneDouble($v)",
    /*  71 */ q"unpackOptApplyOneBoolean($v)",
    /*  72 */ q"unpackOptApplyOneDate($v)",
    /*  73 */ q"unpackOptApplyOneUUID($v)",
    /*  74 */ q"unpackOptApplyOneURI($v)",
    /*  75 */ q"unpackOptApplyOneBigInt($v)",
    /*  76 */ q"unpackOptApplyOneBigDecimal($v)",
    /*  77 */ q"unpackOptApplyManyString($v, vs)",
    /*  78 */ q"unpackOptApplyManyInt($v)",
    /*  79 */ q"unpackOptApplyManyLong($v)",
    /*  80 */ q"unpackOptApplyManyDouble($v)",
    /*  81 */ q"unpackOptApplyManyBoolean($v)",
    /*  82 */ q"unpackOptApplyManyDate($v)",
    /*  83 */ q"unpackOptApplyManyUUID($v)",
    /*  84 */ q"unpackOptApplyManyURI($v)",
    /*  85 */ q"unpackOptApplyManyBigInt($v)",
    /*  86 */ q"unpackOptApplyManyBigDecimal($v)",
    /*  87 */ q"unpackOptApplyMapString($v, vs)",
    /*  88 */ q"unpackOptApplyMapInt($v)",
    /*  89 */ q"unpackOptApplyMapLong($v)",
    /*  90 */ q"unpackOptApplyMapDouble($v)",
    /*  91 */ q"unpackOptApplyMapBoolean($v)",
    /*  92 */ q"unpackOptApplyMapDate($v)",
    /*  93 */ q"unpackOptApplyMapUUID($v)",
    /*  94 */ q"unpackOptApplyMapURI($v)",
    /*  95 */ q"unpackOptApplyMapBigInt($v)",
    /*  96 */ q"unpackOptApplyMapBigDecimal($v)",
    /*  97 */ q"unpackKeyedMapString($v, vs)",
    /*  98 */ q"unpackKeyedMapInt($v)",
    /*  99 */ q"unpackKeyedMapLong($v)",
    /* 100 */ q"unpackKeyedMapDouble($v)",
    /* 101 */ q"unpackKeyedMapBoolean($v)",
    /* 102 */ q"unpackKeyedMapDate($v)",
    /* 103 */ q"unpackKeyedMapUUID($v)",
    /* 104 */ q"unpackKeyedMapURI($v)",
    /* 105 */ q"unpackKeyedMapBigInt($v)",
    /* 106 */ q"unpackKeyedMapBigDecimal($v)",
    /* 107 */ q"unpackKeyedMapAny($v)",
    /* 108 */ q"unpackAggrInt($v)",
    /* 109 */ q"unpackAggrDouble($v)",
    /* 110 */ q"unpackAggrOneListString($v, vs)",
    /* 111 */ q"unpackAggrOneListInt($v)",
    /* 112 */ q"unpackAggrOneListLong($v)",
    /* 113 */ q"unpackAggrOneListDouble($v)",
    /* 114 */ q"unpackAggrOneListBoolean($v)",
    /* 115 */ q"unpackAggrOneListDate($v)",
    /* 116 */ q"unpackAggrOneListUUID($v)",
    /* 117 */ q"unpackAggrOneListURI($v)",
    /* 118 */ q"unpackAggrOneListBigInt($v)",
    /* 119 */ q"unpackAggrOneListBigDecimal($v)",
    /* 120 */ q"unpackAggrManyListString($v, vs)",
    /* 121 */ q"unpackAggrManyListInt($v)",
    /* 122 */ q"unpackAggrManyListLong($v)",
    /* 123 */ q"unpackAggrManyListDouble($v)",
    /* 124 */ q"unpackAggrManyListBoolean($v)",
    /* 125 */ q"unpackAggrManyListDate($v)",
    /* 126 */ q"unpackAggrManyListUUID($v)",
    /* 127 */ q"unpackAggrManyListURI($v)",
    /* 128 */ q"unpackAggrManyListBigInt($v)",
    /* 129 */ q"unpackAggrManyListBigDecimal($v)",
    /* 130 */ q"unpackAggrOneListDistinctString($v, vs)",
    /* 131 */ q"unpackAggrOneListDistinctInt($v)",
    /* 132 */ q"unpackAggrOneListDistinctLong($v)",
    /* 133 */ q"unpackAggrOneListDistinctDouble($v)",
    /* 134 */ q"unpackAggrOneListDistinctBoolean($v)",
    /* 135 */ q"unpackAggrOneListDistinctDate($v)",
    /* 136 */ q"unpackAggrOneListDistinctUUID($v)",
    /* 137 */ q"unpackAggrOneListDistinctURI($v)",
    /* 138 */ q"unpackAggrOneListDistinctBigInt($v)",
    /* 139 */ q"unpackAggrOneListDistinctBigDecimal($v)",
    /* 140 */ q"unpackAggrManyListDistinctString($v, vs)",
    /* 141 */ q"unpackAggrManyListDistinctInt($v)",
    /* 142 */ q"unpackAggrManyListDistinctLong($v)",
    /* 143 */ q"unpackAggrManyListDistinctDouble($v)",
    /* 144 */ q"unpackAggrManyListDistinctBoolean($v)",
    /* 145 */ q"unpackAggrManyListDistinctDate($v)",
    /* 146 */ q"unpackAggrManyListDistinctUUID($v)",
    /* 147 */ q"unpackAggrManyListDistinctURI($v)",
    /* 148 */ q"unpackAggrManyListDistinctBigInt($v)",
    /* 149 */ q"unpackAggrManyListDistinctBigDecimal($v)",
    /* 150 */ q"unpackAggrOneListRandString($v, vs)",
    /* 151 */ q"unpackAggrOneListRandInt($v)",
    /* 152 */ q"unpackAggrOneListRandLong($v)",
    /* 153 */ q"unpackAggrOneListRandDouble($v)",
    /* 154 */ q"unpackAggrOneListRandBoolean($v)",
    /* 155 */ q"unpackAggrOneListRandDate($v)",
    /* 156 */ q"unpackAggrOneListRandUUID($v)",
    /* 157 */ q"unpackAggrOneListRandURI($v)",
    /* 158 */ q"unpackAggrOneListRandBigInt($v)",
    /* 159 */ q"unpackAggrOneListRandBigDecimal($v)",
    /* 160 */ q"unpackAggrManyListRandString($v, vs)",
    /* 161 */ q"unpackAggrManyListRandInt($v)",
    /* 162 */ q"unpackAggrManyListRandLong($v)",
    /* 163 */ q"unpackAggrManyListRandDouble($v)",
    /* 164 */ q"unpackAggrManyListRandBoolean($v)",
    /* 165 */ q"unpackAggrManyListRandDate($v)",
    /* 166 */ q"unpackAggrManyListRandUUID($v)",
    /* 167 */ q"unpackAggrManyListRandURI($v)",
    /* 168 */ q"unpackAggrManyListRandBigInt($v)",
    /* 169 */ q"unpackAggrManyListRandBigDecimal($v)",
    /* 170 */ q"unpackAggrSingleSampleString($v, vs)",
    /* 171 */ q"unpackAggrSingleSampleInt($v)",
    /* 172 */ q"unpackAggrSingleSampleLong($v)",
    /* 173 */ q"unpackAggrSingleSampleDouble($v)",
    /* 174 */ q"unpackAggrSingleSampleBoolean($v)",
    /* 175 */ q"unpackAggrSingleSampleDate($v)",
    /* 176 */ q"unpackAggrSingleSampleUUID($v)",
    /* 177 */ q"unpackAggrSingleSampleURI($v)",
    /* 178 */ q"unpackAggrSingleSampleBigInt($v)",
    /* 179 */ q"unpackAggrSingleSampleBigDecimal($v)",
    /* 180 */ q"unpackAggrOneSingleString($v, vs)",
    /* 181 */ q"unpackAggrOneSingleInt($v)",
    /* 182 */ q"unpackAggrOneSingleLong($v)",
    /* 183 */ q"unpackAggrOneSingleDouble($v)",
    /* 184 */ q"unpackAggrOneSingleBoolean($v)",
    /* 185 */ q"unpackAggrOneSingleDate($v)",
    /* 186 */ q"unpackAggrOneSingleUUID($v)",
    /* 187 */ q"unpackAggrOneSingleURI($v)",
    /* 188 */ q"unpackAggrOneSingleBigInt($v)",
    /* 189 */ q"unpackAggrOneSingleBigDecimal($v)",
    /* 190 */ q"unpackAggrManySingleString($v, vs)",
    /* 191 */ q"unpackAggrManySingleInt($v)",
    /* 192 */ q"unpackAggrManySingleLong($v)",
    /* 193 */ q"unpackAggrManySingleDouble($v)",
    /* 194 */ q"unpackAggrManySingleBoolean($v)",
    /* 195 */ q"unpackAggrManySingleDate($v)",
    /* 196 */ q"unpackAggrManySingleUUID($v)",
    /* 197 */ q"unpackAggrManySingleURI($v)",
    /* 198 */ q"unpackAggrManySingleBigInt($v)",
    /* 199 */ q"unpackAggrManySingleBigDecimal($v)"
  )
}
