package molecule.core.composition

import molecule.core.boilerplate.base._
import molecule.core.boilerplate.dummyTypes._
import molecule.core.boilerplate.out._
import scala.language.higherKinds

/** Transaction meta data on molecule.
  * <br><br>
  * `Tx` takes a transaction meta data molecule with attributes having the transaction id as their entity id.
  * {{{
  *   // Save molecule with transaction data
  *   Person.name("Ben").Tx(MyMetaData.action("add member")).save.eid
  *
  *   // Query for data with transaction meta data - "which persons became members"
  *   Person.name.Tx(MyMetaData.action_("add member")).get === List("Ben")
  * }}}
  */
trait Tx

trait Tx_Obj[props] {
  def Tx: props = ???
}

/** `Tx` interface to save and query tx meta data. */
object Tx {

  trait Tx00[obj[_], props] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_00[obj, props with Tx_Obj[txProps], D01, D02, D02, D03                                                                  ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_01[obj, props with Tx_Obj[txProps], D02, D03, D03, D04, a                                                               ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_02[obj, props with Tx_Obj[txProps], D03, D04, D04, D05, a, b                                                            ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_03[obj, props with Tx_Obj[txProps], D04, D05, D05, D06, a, b, c                                                         ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_04[obj, props with Tx_Obj[txProps], D05, D06, D06, D07, a, b, c, d                                                      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, a, b, c, d, e                                                   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, a, b, c, d, e, f                                                ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, a, b, c, d, e, f, g                                             ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, a, b, c, d, e, f, g, h                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, a, b, c, d, e, f, g, h, i                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, a, b, c, d, e, f, g, h, i, j                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, a, b, c, d, e, f, g, h, i, j, k                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, a, b, c, d, e, f, g, h, i, j, k, l                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (txMetaData: NS18[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (txMetaData: NS19[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (txMetaData: NS20[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] (txMetaData: NS21[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] (txMetaData: NS22[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] = ???
    }
  }

  trait Tx01[obj[_], props, A] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_01[obj, props with Tx_Obj[txProps], D02, D03, D03, D04, A                                                               ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_02[obj, props with Tx_Obj[txProps], D03, D04, D04, D05, A, a                                                            ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_03[obj, props with Tx_Obj[txProps], D04, D05, D05, D06, A, a, b                                                         ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_04[obj, props with Tx_Obj[txProps], D05, D06, D06, D07, A, a, b, c                                                      ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, A, a, b, c, d                                                   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, a, b, c, d, e                                                ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, a, b, c, d, e, f                                             ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, a, b, c, d, e, f, g                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, a, b, c, d, e, f, g, h                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, a, b, c, d, e, f, g, h, i                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, a, b, c, d, e, f, g, h, i, j                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, a, b, c, d, e, f, g, h, i, j, k                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, a, b, c, d, e, f, g, h, i, j, k, l                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, a, b, c, d, e, f, g, h, i, j, k, l, m                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (txMetaData: NS18[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (txMetaData: NS19[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (txMetaData: NS20[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] (txMetaData: NS21[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u] = ???
    }
  }

  trait Tx02[obj[_], props, A, B] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_02[obj, props with Tx_Obj[txProps], D03, D04, D04, D05, A, B                                                            ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_03[obj, props with Tx_Obj[txProps], D04, D05, D05, D06, A, B, a                                                         ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_04[obj, props with Tx_Obj[txProps], D05, D06, D06, D07, A, B, a, b                                                      ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, A, B, a, b, c                                                   ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, B, a, b, c, d                                                ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, a, b, c, d, e                                             ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, a, b, c, d, e, f                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, a, b, c, d, e, f, g                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, a, b, c, d, e, f, g, h                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, a, b, c, d, e, f, g, h, i                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, a, b, c, d, e, f, g, h, i, j                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, a, b, c, d, e, f, g, h, i, j, k                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, a, b, c, d, e, f, g, h, i, j, k, l                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (txMetaData: NS18[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (txMetaData: NS19[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (txMetaData: NS20[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t] = ???
    }
  }

  trait Tx03[obj[_], props, A, B, C] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_03[obj, props with Tx_Obj[txProps], D04, D05, D05, D06, A, B, C                                                         ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_04[obj, props with Tx_Obj[txProps], D05, D06, D06, D07, A, B, C, a                                                      ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, A, B, C, a, b                                                   ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, B, C, a, b, c                                                ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, C, a, b, c, d                                             ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, a, b, c, d, e                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, a, b, c, d, e, f                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, a, b, c, d, e, f, g                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, a, b, c, d, e, f, g, h                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, a, b, c, d, e, f, g, h, i                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, a, b, c, d, e, f, g, h, i, j                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, a, b, c, d, e, f, g, h, i, j, k                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (txMetaData: NS18[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (txMetaData: NS19[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s] = ???
    }
  }

  trait Tx04[obj[_], props, A, B, C, D] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_04[obj, props with Tx_Obj[txProps], D05, D06, D06, D07, A, B, C, D                                                      ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, A, B, C, D, a                                                   ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, B, C, D, a, b                                                ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, C, D, a, b, c                                             ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, D, a, b, c, d                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, a, b, c, d, e                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, a, b, c, d, e, f                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, a, b, c, d, e, f, g                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, a, b, c, d, e, f, g, h                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, a, b, c, d, e, f, g, h, i                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, a, b, c, d, e, f, g, h, i, j                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (txMetaData: NS18[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r] = ???
    }
  }

  trait Tx05[obj[_], props, A, B, C, D, E] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_05[obj, props with Tx_Obj[txProps], D06, D07, D07, D08, A, B, C, D, E                                                   ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, B, C, D, E, a                                                ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, C, D, E, a, b                                             ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, D, E, a, b, c                                          ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, E, a, b, c, d                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, a, b, c, d, e                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, a, b, c, d, e, f                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, a, b, c, d, e, f, g                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, a, b, c, d, e, f, g, h                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, a, b, c, d, e, f, g, h, i                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (txMetaData: NS17[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q] = ???
    }
  }

  trait Tx06[obj[_], props, A, B, C, D, E, F] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_06[obj, props with Tx_Obj[txProps], D07, D08, D08, D09, A, B, C, D, E, F                                                ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, C, D, E, F, a                                             ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, D, E, F, a, b                                          ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, E, F, a, b, c                                       ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, F, a, b, c, d                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, a, b, c, d, e                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, a, b, c, d, e, f                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, a, b, c, d, e, f, g                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, a, b, c, d, e, f, g, h                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (txMetaData: NS16[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p] = ???

    }
  }

  trait Tx07[obj[_], props, A, B, C, D, E, F, G] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_07[obj, props with Tx_Obj[txProps], D08, D09, D09, D10, A, B, C, D, E, F, G                                             ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, D, E, F, G, a                                          ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, E, F, G, a, b                                       ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, F, G, a, b, c                                    ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, G, a, b, c, d                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, a, b, c, d, e                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, a, b, c, d, e, f                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, a, b, c, d, e, f, g                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m, n   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (txMetaData: NS15[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o] = ???
    }
  }

  trait Tx08[obj[_], props, A, B, C, D, E, F, G, H] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_08[obj, props with Tx_Obj[txProps], D09, D10, D10, D11, A, B, C, D, E, F, G, H                                          ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, E, F, G, H, a                                       ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, F, G, H, a, b                                    ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, G, H, a, b, c                                 ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, H, a, b, c, d                              ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, a, b, c, d, e                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, a, b, c, d, e, f                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l, m   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (txMetaData: NS14[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l, m, n] = ???
    }
  }

  trait Tx09[obj[_], props, A, B, C, D, E, F, G, H, I] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_09[obj, props with Tx_Obj[txProps], D10, D11, D11, D12, A, B, C, D, E, F, G, H, I                                       ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, F, G, H, I, a                                    ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, G, H, I, a, b                                 ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, H, I, a, b, c                              ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, I, a, b, c, d                           ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, a, b, c, d, e                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k, l   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (txMetaData: NS13[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k, l, m] = ???
    }
  }

  trait Tx10[obj[_], props, A, B, C, D, E, F, G, H, I, J] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_10[obj, props with Tx_Obj[txProps], D11, D12, D12, D13, A, B, C, D, E, F, G, H, I, J                                    ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, G, H, I, J, a                                 ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, H, I, J, a, b                              ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, I, J, a, b, c                           ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, J, a, b, c, d                        ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j, k   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ] (txMetaData: NS12[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j, k, l] = ???
    }
  }

  trait Tx11[obj[_], props, A, B, C, D, E, F, G, H, I, J, K] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_11[obj, props with Tx_Obj[txProps], D12, D13, D13, D14, A, B, C, D, E, F, G, H, I, J, K                                 ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, H, I, J, K, a                              ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, I, J, K, a, b                           ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, J, K, a, b, c                        ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d                     ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i, j   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ] (txMetaData: NS11[txObj, txProps, a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i, j, k] = ???
    }
  }

  trait Tx12[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_12[obj, props with Tx_Obj[txProps], D13, D14, D14, D15, A, B, C, D, E, F, G, H, I, J, K, L                              ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, I, J, K, L, a                           ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, J, K, L, a, b                        ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c                     ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d                  ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h, i   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ] (txMetaData: NS10[txObj, txProps, a, b, c, d, e, f, g, h, i, j                                    ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h, i, j] = ???
    }
  }

  trait Tx13[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_13[obj, props with Tx_Obj[txProps], D14, D15, D15, D16, A, B, C, D, E, F, G, H, I, J, K, L, M                           ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, J, K, L, M, a                        ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b                     ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c                  ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d               ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g, h   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ] (txMetaData: NS09[txObj, txProps, a, b, c, d, e, f, g, h, i                                       ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g, h, i] = ???
    }
  }

  trait Tx14[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_14[obj, props with Tx_Obj[txProps], D15, D16, D16, D17, A, B, C, D, E, F, G, H, I, J, K, L, M, N                        ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a                     ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b                  ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c               ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d            ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f, g   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g, h                                          ] (txMetaData: NS08[txObj, txProps, a, b, c, d, e, f, g, h                                          ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f, g, h] = ???
    }
  }

  trait Tx15[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_15[obj, props with Tx_Obj[txProps], D16, D17, D17, D18, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                     ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a                  ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b               ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c            ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d         ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e, f   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f, g                                             ] (txMetaData: NS07[txObj, txProps, a, b, c, d, e, f, g                                             ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e, f, g] = ???
    }
  }

  trait Tx16[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_16[obj, props with Tx_Obj[txProps], D17, D18, D18, D19, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                  ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a               ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b            ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c         ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d      ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d, e   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e, f                                                ] (txMetaData: NS06[txObj, txProps, a, b, c, d, e, f                                                ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d, e, f] = ???
    }
  }

  trait Tx17[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_17[obj, props with Tx_Obj[txProps], D18, D19, D19, D20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q               ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a            ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b         ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c      ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c, d   ] = ???
      final def apply[txObj, txProps, a, b, c, d, e                                                   ] (txMetaData: NS05[txObj, txProps, a, b, c, d, e                                                   ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c, d, e] = ???
    }
  }

  trait Tx18[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_18[obj, props with Tx_Obj[txProps], D19, D20, D20, D21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R            ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a         ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b      ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ] (txMetaData: NS03[txObj, txProps, a, b, c                                                         ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b, c   ] = ???
      final def apply[txObj, txProps, a, b, c, d                                                      ] (txMetaData: NS04[txObj, txProps, a, b, c, d                                                      ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b, c, d] = ???
    }
  }

  trait Tx19[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ](txMetaData: NS00[txObj, txProps                                                                    ]): Out_19[obj, props with Tx_Obj[txProps], D20, D21, D21, D22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S         ] = ???
      final def apply[txObj, txProps, a                                                               ](txMetaData: NS01[txObj, txProps, a                                                                 ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a      ] = ???
      final def apply[txObj, txProps, a, b                                                            ](txMetaData: NS02[txObj, txProps, a, b                                                              ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a, b   ] = ???
      final def apply[txObj, txProps, a, b, c                                                         ](txMetaData: NS03[txObj, txProps, a, b, c                                                           ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a, b, c] = ???
    }
  }

  trait Tx20[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_20[obj, props with Tx_Obj[txProps], D21, D22, D22, D23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T      ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, a   ] = ???
      final def apply[txObj, txProps, a, b                                                            ] (txMetaData: NS02[txObj, txProps, a, b                                                            ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, a, b] = ???
    }
  }

  trait Tx21[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_21[obj, props with Tx_Obj[txProps], D22, D23, D23, D24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U   ] = ???
      final def apply[txObj, txProps, a                                                               ] (txMetaData: NS01[txObj, txProps, a                                                               ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, a] = ???
    }
  }

  trait Tx22[obj[_], props, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends Tx {
    object Tx {
      final def apply[txObj, txProps                                                                  ] (txMetaData: NS00[txObj, txProps                                                                  ]): Out_22[obj, props with Tx_Obj[txProps], D23, D24, D24, D25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] = ???
    }
  }
}