package molecule.boilerplate

// Dummy product types used with generated trait types
private[molecule] trait P0
private[molecule] trait P1[A]
private[molecule] trait P2[A, B]
private[molecule] trait P3[A, B, C]
private[molecule] trait P4[A, B, C, D]
private[molecule] trait P5[A, B, C, D, E]
private[molecule] trait P6[A, B, C, D, E, F]
private[molecule] trait P7[A, B, C, D, E, F, G]
private[molecule] trait P8[A, B, C, D, E, F, G, H]
private[molecule] trait P9[A, B, C, D, E, F, G, H, I]
private[molecule] trait P10[A, B, C, D, E, F, G, H, I, J]
private[molecule] trait P11[A, B, C, D, E, F, G, H, I, J, K]
private[molecule] trait P12[A, B, C, D, E, F, G, H, I, J, K, L]
private[molecule] trait P13[A, B, C, D, E, F, G, H, I, J, K, L, M]
private[molecule] trait P14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
private[molecule] trait P15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
private[molecule] trait P16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
private[molecule] trait P17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
private[molecule] trait P18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
private[molecule] trait P19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
private[molecule] trait P20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
private[molecule] trait P21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
private[molecule] trait P22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
private[molecule] trait P23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X]
private[molecule] trait P24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y]
private[molecule] trait P25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z]
private[molecule] trait P26[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z, AA]
private[molecule] trait P27[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z, AA, AB]
