package molecule.core.boilerplate


/** Dummy types for last-arity namespaces or in place of input molecules when not allowed. */
object dummyTypes {
  trait D00[Obj]
  trait D01[Obj, A]
  trait D02[Obj, A, B]
  trait D03[Obj, A, B, C]
  trait D04[Obj, A, B, C, D]
  trait D05[Obj, A, B, C, D, E]
  trait D06[Obj, A, B, C, D, E, F]
  trait D07[Obj, A, B, C, D, E, F, G]
  trait D08[Obj, A, B, C, D, E, F, G, H]
  trait D09[Obj, A, B, C, D, E, F, G, H, I]
  trait D10[Obj, A, B, C, D, E, F, G, H, I, J]
  trait D11[Obj, A, B, C, D, E, F, G, H, I, J, K]
  trait D12[Obj, A, B, C, D, E, F, G, H, I, J, K, L]
  trait D13[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M]
  trait D14[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N]
  trait D15[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
  trait D16[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
  trait D17[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
  trait D18[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
  trait D19[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
  trait D20[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
  trait D21[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
  trait D22[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
  trait D23[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X]
  trait D24[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y]
  trait D25[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z]
  trait D26[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z, AA]
  trait D27[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z, AA, AB]
  trait D28[Obj, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z, AA, AB, AC]
}