/*
* AUTO-GENERATED Molecule DSL for namespace `Datom`
*
* To change:
* 1. Edit data model in molecule.core._2_dsl.generic.dataModel/DatomDataModel
* 2. `sbt clean compile`
* 3. Re-compile project in IDE
*/
package molecule.core.generic.Datom

import java.util.Date
import molecule.core.boilerplate.api._
import molecule.core.boilerplate.attributes._
import molecule.core.boilerplate.base._
import molecule.core.boilerplate.dummyTypes._
import scala.language.higherKinds

trait Datom_2_21[o0[_], p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_[p0]

trait Datom_2_21_L0[o0[_], p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L0[o0, p0 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L0[o0, p0 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L0[o0, p0 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L0[o0, p0 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L0[o0, p0 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L0[o0, p0 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L0[o0, p0 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L0[o0, p0 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L0[o0, p0 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L0[o0, p0 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L0[o0, p0 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L0[o0, p0 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L0[o0, p0 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L0[o0, p0 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L0[o0, p0 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L0[o0, p0 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L0[o0, p0 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L0[o0, p0 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L0[o0, p0 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L0[o0, p0 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L0[o0, p0 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L0[o0, p0 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L0[o0, p0 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L0[o0, p0 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L0[o0, p0 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L0[o0, p0 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L0[o0, p0 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L0[o0, p0 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L0[o0, p0 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L0[o0, p0 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L0[o0, p0 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L0[o0, p0 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L0[o0, p0 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L0[o0, p0 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L0[o0, p0 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L0[o0, p0 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L0[o0, p0, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L1[o0[_], p0, o1[_], p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L1[o0, p0, o1, p1 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L1[o0, p0, o1, p1 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L1[o0, p0, o1, p1 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L1[o0, p0, o1, p1 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L1[o0, p0, o1, p1 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L1[o0, p0, o1, p1 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L1[o0, p0, o1, p1 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L1[o0, p0, o1, p1 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L1[o0, p0, o1, p1 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L1[o0, p0, o1, p1 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L1[o0, p0, o1, p1 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L1[o0, p0, o1, p1 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L1[o0, p0, o1, p1 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L1[o0, p0, o1, p1 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L1[o0, p0, o1, p1 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L1[o0, p0, o1, p1 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L1[o0, p0, o1, p1 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L1[o0, p0, o1, p1 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L1[o0, p0, o1, p1, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L2[o0[_], p0, o1[_], p1, o2[_], p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L2[o0, p0, o1, p1, o2, p2 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L2[o0, p0, o1, p1, o2, p2 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L2[o0, p0, o1, p1, o2, p2 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L2[o0, p0, o1, p1, o2, p2, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L3[o0[_], p0, o1[_], p1, o2[_], p2, o3[_], p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2 with o3[p3]]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L3[o0, p0, o1, p1, o2, p2, o3, p3 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L3[o0, p0, o1, p1, o2, p2, o3, p3, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L4[o0[_], p0, o1[_], p1, o2[_], p2, o3[_], p3, o4[_], p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2 with o3[p3 with o4[p4]]]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L4[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L5[o0[_], p0, o1[_], p1, o2[_], p2, o3[_], p3, o4[_], p4, o5[_], p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2 with o3[p3 with o4[p4 with o5[p5]]]]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L5[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L6[o0[_], p0, o1[_], p1, o2[_], p2, o3[_], p3, o4[_], p4, o5[_], p5, o6[_], p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2 with o3[p3 with o4[p4 with o5[p5 with o6[p6]]]]]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L6[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}


trait Datom_2_21_L7[o0[_], p0, o1[_], p1, o2[_], p2, o3[_], p3, o4[_], p4, o5[_], p5, o6[_], p6, o7[_], p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Datom_2_21[o0, p0 with o1[p1 with o2[p2 with o3[p3 with o4[p4 with o5[p5 with o6[p6 with o7[p7]]]]]]], I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {

  final lazy val e          : OneLong    [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val a          : OneString  [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, String ] with Indexed = ???
  final lazy val v          : OneAny     [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Any    ] with Indexed = ???
  final lazy val t          : OneLong    [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val tx         : OneLong    [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Long   ] with Indexed = ???
  final lazy val txInstant  : OneDate    [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Date   ] with Indexed = ???
  final lazy val op         : OneBoolean [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean], Datom_3_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Boolean] with Indexed = ???
  
  final lazy val e$         : OneLong$   [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val a$         : OneString$ [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[String ]] with Indexed = ???
  final lazy val v$         : OneAny$    [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Any    ]] with Indexed = ???
  final lazy val t$         : OneLong$   [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t$        , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val tx$        : OneLong$   [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Long   ]] with Indexed = ???
  final lazy val txInstant$ : OneDate$   [Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant$, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Date   ]] with Indexed = ???
  final lazy val op$        : OneBoolean$[Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]]] with Datom_2_22_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op$       , I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Option[Boolean]] with Indexed = ???
  
  final lazy val e_         : OneLong    [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_e        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val a_         : OneString  [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_a        , I1, I2, String , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val v_         : OneAny     [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_v        , I1, I2, Any    , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val t_         : OneLong    [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_t        , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val tx_        : OneLong    [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_tx       , I1, I2, Long   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val txInstant_ : OneDate    [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_txInstant, I1, I2, Date   , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  final lazy val op_        : OneBoolean [Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U], Datom_3_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7 with Datom_op       , I1, I2, Boolean, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]] with Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with Indexed = ???
  
  final def Self: Datom_2_21_L7[o0, p0, o1, p1, o2, p2, o3, p3, o4, p4, o5, p5, o6, p6, o7, p7, I1, I2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] with SelfJoin = ???
}

     
