package molecule.datomic.base.marshalling.pack

import java.util.{Iterator => jIterator}


trait PackLambdas extends PackTypes with PackAggr {

  // Array with all pack lambdas for fast lookup
  val packLambdas: Array[jIterator[_] => Unit] = Array(
    /*   0 */ packOneString,
    /*   1 */ packOne, // packOneInt,
    /*   2 */ packOne, // packOneInt, // (slot for int2 cast)
    /*   3 */ packOne, // packOneLong,
    /*   4 */ packOne, // packOneDouble,
    /*   5 */ packOne, // packOneBoolean,
    /*   6 */ packOneDate,
    /*   7 */ packOne, // packOneUUID,
    /*   8 */ packOne, // packOneURI,
    /*   9 */ packOne, // packOneBigInt,
    /*  10 */ packOne, // packOneBigDecimal,
    /*  11 */ packOneAny,
    /*  12 */ packOptOneEnum,
    /*  13 */ packOptOneString,
    /*  14 */ packOptOne, // packOptOneInt,
    /*  15 */ packOptOne, // packOptOneLong,
    /*  16 */ packOptOne, // packOptOneDouble,
    /*  17 */ packOptOne, // packOptOneBoolean,
    /*  18 */ packOptOneDate,
    /*  19 */ packOptOne, // packOptOneUUID,
    /*  20 */ packOptOne, // packOptOneURI,
    /*  21 */ packOptOne, // packOptOneBigInt,
    /*  22 */ packOptOne, // packOptOneBigDecimal,
    /*  23 */ packOptOneRefAttr,
    /*  24 */ packManyEnum,
    /*  25 */ packManyString,
    /*  26 */ packMany, // packManyInt,
    /*  27 */ packMany, // packManyLong,
    /*  28 */ packMany, // packManyDouble,
    /*  29 */ packMany, // packManyBoolean,
    /*  30 */ packManyDate,
    /*  31 */ packMany, // packManyUUID,
    /*  32 */ packMany, // packManyURI,
    /*  33 */ packMany, // packManyBigInt,
    /*  34 */ packMany, // packManyBigDecimal,
    /*  35 */ packOptManyEnum,
    /*  36 */ packOptManyString,
    /*  37 */ packOptMany, // packOptManyInt,
    /*  38 */ packOptMany, // packOptManyLong,
    /*  39 */ packOptMany, // packOptManyDouble,
    /*  40 */ packOptMany, // packOptManyBoolean,
    /*  41 */ packOptManyDate,
    /*  42 */ packOptMany, // packOptManyUUID,
    /*  43 */ packOptMany, // packOptManyURI,
    /*  44 */ packOptMany, // packOptManyBigInt,
    /*  45 */ packOptMany, // packOptManyBigDecimal,
    /*  46 */ packOptManyRefAttr,
    /*  47 */ packMapString,
    /*  48 */ packMap, // packMapInt,
    /*  49 */ packMap, // packMapLong,
    /*  50 */ packMap, // packMapDouble,
    /*  51 */ packMap, // packMapBoolean,
    /*  52 */ packMap, // packMapDate,
    /*  53 */ packMap, // packMapUUID,
    /*  54 */ packMap, // packMapURI,
    /*  55 */ packMap, // packMapBigInt,
    /*  56 */ packMap, // packMapBigDecimal,
    /*  57 */ packOptMapString,
    /*  58 */ packOptMap, // packOptMapInt,
    /*  59 */ packOptMap, // packOptMapLong,
    /*  60 */ packOptMap, // packOptMapDouble,
    /*  61 */ packOptMap, // packOptMapBoolean,
    /*  62 */ packOptMap, // packOptMapDate,
    /*  63 */ packOptMap, // packOptMapUUID,
    /*  64 */ packOptMap, // packOptMapURI,
    /*  65 */ packOptMap, // packOptMapBigInt,
    /*  66 */ packOptMap, // packOptMapBigDecimal,
    /*  67 */ packOptApplyOneString,
    /*  68 */ packOptApplyOne, // packOptApplyOneInt,
    /*  69 */ packOptApplyOne, // packOptApplyOneLong,
    /*  70 */ packOptApplyOne, // packOptApplyOneDouble,
    /*  71 */ packOptApplyOne, // packOptApplyOneBoolean,
    /*  72 */ packOptApplyOneDate, // packOptApplyOneDate,
    /*  73 */ packOptApplyOne, // packOptApplyOneUUID,
    /*  74 */ packOptApplyOne, // packOptApplyOneURI,
    /*  75 */ packOptApplyOne, // packOptApplyOneBigInt,
    /*  76 */ packOptApplyOne, // packOptApplyOneBigDecimal,
    /*  77 */ packOptApplyManyString,
    /*  78 */ packOptApplyMany, // packOptApplyManyInt,
    /*  79 */ packOptApplyMany, // packOptApplyManyLong,
    /*  80 */ packOptApplyMany, // packOptApplyManyDouble,
    /*  81 */ packOptApplyMany, // packOptApplyManyBoolean,
    /*  82 */ packOptApplyManyDate,
    /*  83 */ packOptApplyMany, // packOptApplyManyUUID,
    /*  84 */ packOptApplyMany, // packOptApplyManyURI,
    /*  85 */ packOptApplyMany, // packOptApplyManyBigInt,
    /*  86 */ packOptApplyMany, // packOptApplyManyBigDecimal,
    /*  87 */ packOptApplyMapString,
    /*  88 */ packOptApplyMap, // packOptApplyMapInt,
    /*  89 */ packOptApplyMap, // packOptApplyMapLong,
    /*  90 */ packOptApplyMap, // packOptApplyMapDouble,
    /*  91 */ packOptApplyMap, // packOptApplyMapBoolean,
    /*  92 */ packOptApplyMapDate,
    /*  93 */ packOptApplyMap, // packOptApplyMapUUID,
    /*  94 */ packOptApplyMap, // packOptApplyMapURI,
    /*  95 */ packOptApplyMap, // packOptApplyMapBigInt,
    /*  96 */ packOptApplyMap, // packOptApplyMapBigDecimal,
    /*  97 */ packKeyedMapString,
    /*  98 */ packKeyedMap, // packKeyedMapInt,
    /*  99 */ packKeyedMap, // packKeyedMapLong,
    /* 100 */ packKeyedMap, // packKeyedMapDouble,
    /* 101 */ packKeyedMap, // packKeyedMapBoolean,
    /* 102 */ packKeyedMapDate,
    /* 103 */ packKeyedMap, // packKeyedMapUUID,
    /* 104 */ packKeyedMap, // packKeyedMapURI,
    /* 105 */ packKeyedMap, // packKeyedMapBigInt,
    /* 106 */ packKeyedMap, // packKeyedMapBigDecimal,
    /* 107 */ packKeyedMapAny,
    /* 108 */ packAggrInt,
    /* 109 */ packAggrDouble,
    /* 110 */ packAggrOneListString,
    /* 111 */ packAggrOneList, // packAggrOneListInt,
    /* 112 */ packAggrOneList, // packAggrOneListLong,
    /* 113 */ packAggrOneList, // packAggrOneListDouble,
    /* 114 */ packAggrOneList, // packAggrOneListBoolean,
    /* 115 */ packAggrOneListDate,
    /* 116 */ packAggrOneList, // packAggrOneListUUID,
    /* 117 */ packAggrOneList, // packAggrOneListURI,
    /* 118 */ packAggrOneList, // packAggrOneListBigInt,
    /* 119 */ packAggrOneList, // packAggrOneListBigDecimal,
    /* 120 */ packAggrManyListString,
    /* 121 */ packAggrManyList, // packAggrManyListInt,
    /* 122 */ packAggrManyList, // packAggrManyListLong,
    /* 123 */ packAggrManyList, // packAggrManyListDouble,
    /* 124 */ packAggrManyList, // packAggrManyListBoolean,
    /* 125 */ packAggrManyListDate,
    /* 126 */ packAggrManyList, // packAggrManyListUUID,
    /* 127 */ packAggrManyList, // packAggrManyListURI,
    /* 128 */ packAggrManyList, // packAggrManyListBigInt,
    /* 129 */ packAggrManyList, // packAggrManyListBigDecimal,
    /* 130 */ packAggrOneListDistinctString,
    /* 131 */ packAggrOneListDistinct, // packAggrOneListDistinctInt,
    /* 132 */ packAggrOneListDistinct, // packAggrOneListDistinctLong,
    /* 133 */ packAggrOneListDistinct, // packAggrOneListDistinctDouble,
    /* 134 */ packAggrOneListDistinct, // packAggrOneListDistinctBoolean,
    /* 135 */ packAggrOneListDistinctDate,
    /* 136 */ packAggrOneListDistinct, // packAggrOneListDistinctUUID,
    /* 137 */ packAggrOneListDistinct, // packAggrOneListDistinctURI,
    /* 138 */ packAggrOneListDistinct, // packAggrOneListDistinctBigInt,
    /* 139 */ packAggrOneListDistinct, // packAggrOneListDistinctBigDecimal,
    /* 140 */ packAggrManyListDistinctString,
    /* 141 */ packAggrManyListDistinct, // packAggrManyListDistinctInt,
    /* 142 */ packAggrManyListDistinct, // packAggrManyListDistinctLong,
    /* 143 */ packAggrManyListDistinct, // packAggrManyListDistinctDouble,
    /* 144 */ packAggrManyListDistinct, // packAggrManyListDistinctBoolean,
    /* 145 */ packAggrManyListDistinctDate,
    /* 146 */ packAggrManyListDistinct, // packAggrManyListDistinctUUID,
    /* 147 */ packAggrManyListDistinct, // packAggrManyListDistinctURI,
    /* 148 */ packAggrManyListDistinct, // packAggrManyListDistinctBigInt,
    /* 149 */ packAggrManyListDistinct, // packAggrManyListDistinctBigDecimal,
    /* 150 */ packAggrOneListRandString,
    /* 151 */ packAggrOneListRand, // packAggrOneListRandInt,
    /* 152 */ packAggrOneListRand, // packAggrOneListRandLong,
    /* 153 */ packAggrOneListRand, // packAggrOneListRandDouble,
    /* 154 */ packAggrOneListRand, // packAggrOneListRandBoolean,
    /* 155 */ packAggrOneListRandDate,
    /* 156 */ packAggrOneListRand, // packAggrOneListRandUUID,
    /* 157 */ packAggrOneListRand, // packAggrOneListRandURI,
    /* 158 */ packAggrOneListRand, // packAggrOneListRandBigInt,
    /* 159 */ packAggrOneListRand, // packAggrOneListRandBigDecimal,
    /* 160 */ packAggrManyListRandString,
    /* 161 */ packAggrManyListRand, // packAggrManyListRandInt,
    /* 162 */ packAggrManyListRand, // packAggrManyListRandLong,
    /* 163 */ packAggrManyListRand, // packAggrManyListRandDouble,
    /* 164 */ packAggrManyListRand, // packAggrManyListRandBoolean,
    /* 165 */ packAggrManyListRandDate,
    /* 166 */ packAggrManyListRand, // packAggrManyListRandUUID,
    /* 167 */ packAggrManyListRand, // packAggrManyListRandURI,
    /* 168 */ packAggrManyListRand, // packAggrManyListRandBigInt,
    /* 169 */ packAggrManyListRand, // packAggrManyListRandBigDecimal,
    /* 170 */ packAggrSingleSampleString,
    /* 171 */ packAggrSingleSample, // packAggrSingleSampleInt,
    /* 172 */ packAggrSingleSample, // packAggrSingleSampleLong,
    /* 173 */ packAggrSingleSample, // packAggrSingleSampleDouble,
    /* 174 */ packAggrSingleSample, // packAggrSingleSampleBoolean,
    /* 175 */ packAggrSingleSampleDate,
    /* 176 */ packAggrSingleSample, // packAggrSingleSampleUUID,
    /* 177 */ packAggrSingleSample, // packAggrSingleSampleURI,
    /* 178 */ packAggrSingleSample, // packAggrSingleSampleBigInt,
    /* 179 */ packAggrSingleSample, // packAggrSingleSampleBigDecimal,
    /* 180 */ packAggrOneSingleString,
    /* 181 */ packAggrOneSingle, // packAggrOneSingleInt,
    /* 182 */ packAggrOneSingle, // packAggrOneSingleLong,
    /* 183 */ packAggrOneSingle, // packAggrOneSingleDouble,
    /* 184 */ packAggrOneSingle, // packAggrOneSingleBoolean,
    /* 185 */ packAggrOneSingleDate,
    /* 186 */ packAggrOneSingle, // packAggrOneSingleUUID,
    /* 187 */ packAggrOneSingle, // packAggrOneSingleURI,
    /* 188 */ packAggrOneSingle, // packAggrOneSingleBigInt,
    /* 189 */ packAggrOneSingle, // packAggrOneSingleBigDecimal,
    /* 190 */ packAggrManySingleString,
    /* 191 */ packAggrManySingle, // packAggrManySingleInt,
    /* 192 */ packAggrManySingle, // packAggrManySingleLong,
    /* 193 */ packAggrManySingle, // packAggrManySingleDouble,
    /* 194 */ packAggrManySingle, // packAggrManySingleBoolean,
    /* 195 */ packAggrManySingleDate,
    /* 196 */ packAggrManySingle, // packAggrManySingleUUID,
    /* 197 */ packAggrManySingle, // packAggrManySingleURI,
    /* 198 */ packAggrManySingle, // packAggrManySingleBigInt,
    /* 199 */ packAggrManySingle, // packAggrManySingleBigDecimal
  )
}
