package molecule.core.marshalling

import java.net.URI
import java.util.{Date, UUID}

case class QueryResult(
  oneString: Seq[Array[String]] = Nil,
  oneInt: Seq[Array[Int]] = Nil,
  oneLong: Seq[Array[Long]] = Nil,
  oneFloat: Seq[Array[Float]] = Nil,
  oneDouble: Seq[Array[Double]] = Nil,
  oneBoolean: Seq[Array[Boolean]] = Nil,
  oneBigInt: Seq[Array[BigInt]] = Nil,
  oneBigDecimal: Seq[Array[BigDecimal]] = Nil,
  oneDate: Seq[Array[Date]] = Nil,
  oneUUID: Seq[Array[UUID]] = Nil,
  oneURI: Seq[Array[URI]] = Nil,

  oneOptString: Seq[Array[Option[String]]] = Nil,
  oneOptInt: Seq[Array[Option[Int]]] = Nil,
  oneOptLong: Seq[Array[Option[Long]]] = Nil,
  oneOptFloat: Seq[Array[Option[Float]]] = Nil,
  oneOptDouble: Seq[Array[Option[Double]]] = Nil,
  oneOptBoolean: Seq[Array[Option[Boolean]]] = Nil,
  oneOptBigInt: Seq[Array[Option[BigInt]]] = Nil,
  oneOptBigDecimal: Seq[Array[Option[BigDecimal]]] = Nil,
  oneOptDate: Seq[Array[Option[Date]]] = Nil,
  oneOptUUID: Seq[Array[Option[UUID]]] = Nil,
  oneOptURI: Seq[Array[Option[URI]]] = Nil,

  manyString: Seq[Array[Set[String]]] = Nil,
  manyInt: Seq[Array[Set[Int]]] = Nil,
  manyLong: Seq[Array[Set[Long]]] = Nil,
  manyFloat: Seq[Array[Set[Float]]] = Nil,
  manyDouble: Seq[Array[Set[Double]]] = Nil,
  manyBoolean: Seq[Array[Set[Boolean]]] = Nil,
  manyBigInt: Seq[Array[Set[BigInt]]] = Nil,
  manyBigDecimal: Seq[Array[Set[BigDecimal]]] = Nil,
  manyDate: Seq[Array[Set[Date]]] = Nil,
  manyUUID: Seq[Array[Set[UUID]]] = Nil,
  manyURI: Seq[Array[Set[URI]]] = Nil,

  manyOptString: Seq[Array[Option[Set[String]]]] = Nil,
  manyOptInt: Seq[Array[Option[Set[Int]]]] = Nil,
  manyOptLong: Seq[Array[Option[Set[Long]]]] = Nil,
  manyOptFloat: Seq[Array[Option[Set[Float]]]] = Nil,
  manyOptDouble: Seq[Array[Option[Set[Double]]]] = Nil,
  manyOptBoolean: Seq[Array[Option[Set[Boolean]]]] = Nil,
  manyOptBigInt: Seq[Array[Option[Set[BigInt]]]] = Nil,
  manyOptBigDecimal: Seq[Array[Option[Set[BigDecimal]]]] = Nil,
  manyOptDate: Seq[Array[Option[Set[Date]]]] = Nil,
  manyOptUUID: Seq[Array[Option[Set[UUID]]]] = Nil,
  manyOptURI: Seq[Array[Option[Set[URI]]]] = Nil,

  mapString: Seq[Array[Map[String, String]]] = Nil,
  mapInt: Seq[Array[Map[String, Int]]] = Nil,
  mapLong: Seq[Array[Map[String, Long]]] = Nil,
  mapFloat: Seq[Array[Map[String, Float]]] = Nil,
  mapDouble: Seq[Array[Map[String, Double]]] = Nil,
  mapBoolean: Seq[Array[Map[String, Boolean]]] = Nil,
  mapBigInt: Seq[Array[Map[String, BigInt]]] = Nil,
  mapBigDecimal: Seq[Array[Map[String, BigDecimal]]] = Nil,
  mapDate: Seq[Array[Map[String, Date]]] = Nil,
  mapUUID: Seq[Array[Map[String, UUID]]] = Nil,
  mapURI: Seq[Array[Map[String, URI]]] = Nil,

  mapOptString: Seq[Array[Option[Map[String, String]]]] = Nil,
  mapOptInt: Seq[Array[Option[Map[String, Int]]]] = Nil,
  mapOptLong: Seq[Array[Option[Map[String, Long]]]] = Nil,
  mapOptFloat: Seq[Array[Option[Map[String, Float]]]] = Nil,
  mapOptDouble: Seq[Array[Option[Map[String, Double]]]] = Nil,
  mapOptBoolean: Seq[Array[Option[Map[String, Boolean]]]] = Nil,
  mapOptBigInt: Seq[Array[Option[Map[String, BigInt]]]] = Nil,
  mapOptBigDecimal: Seq[Array[Option[Map[String, BigDecimal]]]] = Nil,
  mapOptDate: Seq[Array[Option[Map[String, Date]]]] = Nil,
  mapOptUUID: Seq[Array[Option[Map[String, UUID]]]] = Nil,
  mapOptURI: Seq[Array[Option[Map[String, URI]]]] = Nil,

  rowCountAll: Int,
  maxRows: Int,
  queryMs: Long
)