package molecule.core.marshalling

import java.net.URI
import java.util.{Date, UUID}

case class QueryResult(
  oneString: Seq[Array[String]] = Nil,
  oneInt: Seq[Array[Int]] = Nil,
  oneLong: Seq[Array[Long]] = Nil,
  oneFloat: Seq[Array[Float]] = Nil,
  oneDouble: Seq[Array[Double]] = Nil,
  oneBoolean: Seq[Array[Boolean]] = Nil,
  oneBigInt: Seq[Array[BigInt]] = Nil,
  oneBigDecimal: Seq[Array[BigDecimal]] = Nil,
  oneDate: Seq[Array[Date]] = Nil,
  oneUUID: Seq[Array[UUID]] = Nil,
  oneURI: Seq[Array[URI]] = Nil,

  optOneString: Seq[Array[Option[String]]] = Nil,
  optOneInt: Seq[Array[Option[Int]]] = Nil,
  optOneLong: Seq[Array[Option[Long]]] = Nil,
  optOneFloat: Seq[Array[Option[Float]]] = Nil,
  optOneDouble: Seq[Array[Option[Double]]] = Nil,
  optOneBoolean: Seq[Array[Option[Boolean]]] = Nil,
  optOneBigInt: Seq[Array[Option[BigInt]]] = Nil,
  optOneBigDecimal: Seq[Array[Option[BigDecimal]]] = Nil,
  optOneDate: Seq[Array[Option[Date]]] = Nil,
  optOneUUID: Seq[Array[Option[UUID]]] = Nil,
  optOneURI: Seq[Array[Option[URI]]] = Nil,

  manyString: Seq[Array[Set[String]]] = Nil,
  manyInt: Seq[Array[Set[Int]]] = Nil,
  manyLong: Seq[Array[Set[Long]]] = Nil,
  manyFloat: Seq[Array[Set[Float]]] = Nil,
  manyDouble: Seq[Array[Set[Double]]] = Nil,
  manyBoolean: Seq[Array[Set[Boolean]]] = Nil,
  manyBigInt: Seq[Array[Set[BigInt]]] = Nil,
  manyBigDecimal: Seq[Array[Set[BigDecimal]]] = Nil,
  manyDate: Seq[Array[Set[Date]]] = Nil,
  manyUUID: Seq[Array[Set[UUID]]] = Nil,
  manyURI: Seq[Array[Set[URI]]] = Nil,

  optManyString: Seq[Array[Option[Set[String]]]] = Nil,
  optManyInt: Seq[Array[Option[Set[Int]]]] = Nil,
  optManyLong: Seq[Array[Option[Set[Long]]]] = Nil,
  optManyFloat: Seq[Array[Option[Set[Float]]]] = Nil,
  optManyDouble: Seq[Array[Option[Set[Double]]]] = Nil,
  optManyBoolean: Seq[Array[Option[Set[Boolean]]]] = Nil,
  optManyBigInt: Seq[Array[Option[Set[BigInt]]]] = Nil,
  optManyBigDecimal: Seq[Array[Option[Set[BigDecimal]]]] = Nil,
  optManyDate: Seq[Array[Option[Set[Date]]]] = Nil,
  optManyUUID: Seq[Array[Option[Set[UUID]]]] = Nil,
  optManyURI: Seq[Array[Option[Set[URI]]]] = Nil,

  mapString: Seq[Array[Map[String, String]]] = Nil,
  mapInt: Seq[Array[Map[String, Int]]] = Nil,
  mapLong: Seq[Array[Map[String, Long]]] = Nil,
  mapFloat: Seq[Array[Map[String, Float]]] = Nil,
  mapDouble: Seq[Array[Map[String, Double]]] = Nil,
  mapBoolean: Seq[Array[Map[String, Boolean]]] = Nil,
  mapBigInt: Seq[Array[Map[String, BigInt]]] = Nil,
  mapBigDecimal: Seq[Array[Map[String, BigDecimal]]] = Nil,
  mapDate: Seq[Array[Map[String, Date]]] = Nil,
  mapUUID: Seq[Array[Map[String, UUID]]] = Nil,
  mapURI: Seq[Array[Map[String, URI]]] = Nil,

  optMapString: Seq[Array[Option[Map[String, String]]]] = Nil,
  optMapInt: Seq[Array[Option[Map[String, Int]]]] = Nil,
  optMapLong: Seq[Array[Option[Map[String, Long]]]] = Nil,
  optMapFloat: Seq[Array[Option[Map[String, Float]]]] = Nil,
  optMapDouble: Seq[Array[Option[Map[String, Double]]]] = Nil,
  optMapBoolean: Seq[Array[Option[Map[String, Boolean]]]] = Nil,
  optMapBigInt: Seq[Array[Option[Map[String, BigInt]]]] = Nil,
  optMapBigDecimal: Seq[Array[Option[Map[String, BigDecimal]]]] = Nil,
  optMapDate: Seq[Array[Option[Map[String, Date]]]] = Nil,
  optMapUUID: Seq[Array[Option[Map[String, UUID]]]] = Nil,
  optMapURI: Seq[Array[Option[Map[String, URI]]]] = Nil,

  rowCountAll: Int,
  maxRows: Int,
  queryMs: Long
)