package molecule.dsl

import molecule.dsl.actions._
import molecule.api._
import scala.language.higherKinds

trait Branch

trait Branch0[Ns0, Ns1[_]] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns0                                                                                          = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns1[a                                                                                      ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_2[P2, P3, P3, P4, a, b                                                                 ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_3[P3, P4, P4, P5, a, b, c                                                              ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_4[P4, P5, P5, P6, a, b, c, d                                                           ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_5[P5, P6, P6, P7, a, b, c, d, e                                                        ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_6[P6, P7, P7, P8, a, b, c, d, e, f                                                     ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_7[P7, P8, P8, P9, a, b, c, d, e, f, g                                                  ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_8[P8, P9, P9, P10, a, b, c, d, e, f, g, h                                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_9[P9, P10, P10, P11, a, b, c, d, e, f, g, h, i                                         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_10[P10, P11, P11, P12, a, b, c, d, e, f, g, h, i, j                                    ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_11[P11, P12, P12, P13, a, b, c, d, e, f, g, h, i, j, k                                 ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_12[P12, P13, P13, P14, a, b, c, d, e, f, g, h, i, j, k, l                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_13[P13, P14, P14, P15, a, b, c, d, e, f, g, h, i, j, k, l, m                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_14[P14, P15, P15, P16, a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_15[P15, P16, P16, P17, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_16[P16, P17, P17, P18, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_17[P17, P18, P18, P19, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (branched: NS18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_18[P18, P19, P19, P20, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (branched: NS19[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_19[P19, P20, P20, P21, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (branched: NS20[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_20[P20, P21, P21, P22, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] (branched: NS21[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ]): Out_21[P21, P22, P22, P23, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] (branched: NS22[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v]): Out_22[P22, P23, P23, P24, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] = ???
}

trait Branch1[Ns1[_], Ns2[_,_], A] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns1[A                                                                                      ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns2[A, a                                                                                   ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_3[P3, P4, P4, P5, A, a, b                                                              ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_4[P4, P5, P5, P6, A, a, b, c                                                           ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_5[P5, P6, P6, P7, A, a, b, c, d                                                        ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_6[P6, P7, P7, P8, A, a, b, c, d, e                                                     ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_7[P7, P8, P8, P9, A, a, b, c, d, e, f                                                  ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_8[P8, P9, P9, P10, A, a, b, c, d, e, f, g                                              ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_9[P9, P10, P10, P11, A, a, b, c, d, e, f, g, h                                         ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_10[P10, P11, P11, P12, A, a, b, c, d, e, f, g, h, i                                    ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_11[P11, P12, P12, P13, A, a, b, c, d, e, f, g, h, i, j                                 ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_12[P12, P13, P13, P14, A, a, b, c, d, e, f, g, h, i, j, k                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_13[P13, P14, P14, P15, A, a, b, c, d, e, f, g, h, i, j, k, l                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_14[P14, P15, P15, P16, A, a, b, c, d, e, f, g, h, i, j, k, l, m                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_15[P15, P16, P16, P17, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_16[P16, P17, P17, P18, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_17[P17, P18, P18, P19, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_18[P18, P19, P19, P20, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (branched: NS18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_19[P19, P20, P20, P21, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (branched: NS19[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_20[P20, P21, P21, P22, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (branched: NS20[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_21[P21, P22, P22, P23, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] (branched: NS21[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ]): Out_22[P22, P23, P23, P24, A, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u] = ???
}

trait Branch2[Ns2[_,_], Ns3[_,_,_], A, B] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns2[A, B                                                                                   ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns3[A, B, a                                                                                ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_4[P4, P5, P5, P6, A, B, a, b                                                           ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_5[P5, P6, P6, P7, A, B, a, b, c                                                        ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_6[P6, P7, P7, P8, A, B, a, b, c, d                                                     ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_7[P7, P8, P8, P9, A, B, a, b, c, d, e                                                  ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_8[P8, P9, P9, P10, A, B, a, b, c, d, e, f                                              ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_9[P9, P10, P10, P11, A, B, a, b, c, d, e, f, g                                         ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_10[P10, P11, P11, P12, A, B, a, b, c, d, e, f, g, h                                    ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_11[P11, P12, P12, P13, A, B, a, b, c, d, e, f, g, h, i                                 ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_12[P12, P13, P13, P14, A, B, a, b, c, d, e, f, g, h, i, j                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_13[P13, P14, P14, P15, A, B, a, b, c, d, e, f, g, h, i, j, k                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_14[P14, P15, P15, P16, A, B, a, b, c, d, e, f, g, h, i, j, k, l                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_15[P15, P16, P16, P17, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_16[P16, P17, P17, P18, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_17[P17, P18, P18, P19, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_18[P18, P19, P19, P20, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_19[P19, P20, P20, P21, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (branched: NS18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_20[P20, P21, P21, P22, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (branched: NS19[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_21[P21, P22, P22, P23, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (branched: NS20[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Out_22[P22, P23, P23, P24, A, B, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t] = ???
}

trait Branch3[Ns3[_,_,_], Ns4[_,_,_,_], A, B, C] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns3[A, B, C                                                                                ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns4[A, B, C, a                                                                             ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_5[P5, P6, P6, P7, A, B, C, a, b                                                        ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_6[P6, P7, P7, P8, A, B, C, a, b, c                                                     ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_7[P7, P8, P8, P9, A, B, C, a, b, c, d                                                  ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_8[P8, P9, P9, P10, A, B, C, a, b, c, d, e                                              ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_9[P9, P10, P10, P11, A, B, C, a, b, c, d, e, f                                         ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_10[P10, P11, P11, P12, A, B, C, a, b, c, d, e, f, g                                    ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_11[P11, P12, P12, P13, A, B, C, a, b, c, d, e, f, g, h                                 ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_12[P12, P13, P13, P14, A, B, C, a, b, c, d, e, f, g, h, i                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_13[P13, P14, P14, P15, A, B, C, a, b, c, d, e, f, g, h, i, j                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_14[P14, P15, P15, P16, A, B, C, a, b, c, d, e, f, g, h, i, j, k                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_15[P15, P16, P16, P17, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_16[P16, P17, P17, P18, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_17[P17, P18, P18, P19, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_18[P18, P19, P19, P20, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_19[P19, P20, P20, P21, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_20[P20, P21, P21, P22, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (branched: NS18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_21[P21, P22, P22, P23, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (branched: NS19[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Out_22[P22, P23, P23, P24, A, B, C, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s] = ???
}

trait Branch4[Ns4[_,_,_,_], Ns5[_,_,_,_,_], A, B, C, D] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns4[A, B, C, D                                                                             ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns5[A, B, C, D, a                                                                          ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_6[P6, P7, P7, P8, A, B, C, D, a, b                                                     ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_7[P7, P8, P8, P9, A, B, C, D, a, b, c                                                  ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_8[P8, P9, P9, P10, A, B, C, D, a, b, c, d                                              ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_9[P9, P10, P10, P11, A, B, C, D, a, b, c, d, e                                         ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_10[P10, P11, P11, P12, A, B, C, D, a, b, c, d, e, f                                    ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_11[P11, P12, P12, P13, A, B, C, D, a, b, c, d, e, f, g                                 ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_12[P12, P13, P13, P14, A, B, C, D, a, b, c, d, e, f, g, h                              ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_13[P13, P14, P14, P15, A, B, C, D, a, b, c, d, e, f, g, h, i                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_14[P14, P15, P15, P16, A, B, C, D, a, b, c, d, e, f, g, h, i, j                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_15[P15, P16, P16, P17, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_16[P16, P17, P17, P18, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_17[P17, P18, P18, P19, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_18[P18, P19, P19, P20, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_19[P19, P20, P20, P21, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_20[P20, P21, P21, P22, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_21[P21, P22, P22, P23, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (branched: NS18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Out_22[P22, P23, P23, P24, A, B, C, D, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r] = ???
}

trait Branch5[Ns5[_,_,_,_,_], Ns6[_,_,_,_,_,_], A, B, C, D, E] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns5[A, B, C, D, E                                                                          ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns6[A, B, C, D, E, a                                                                       ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_7[P7, P8, P8, P9, A, B, C, D, E, a, b                                                  ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_8[P8, P9, P9, P10, A, B, C, D, E, a, b, c                                              ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_9[P9, P10, P10, P11, A, B, C, D, E, a, b, c, d                                         ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_10[P10, P11, P11, P12, A, B, C, D, E, a, b, c, d, e                                    ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_11[P11, P12, P12, P13, A, B, C, D, E, a, b, c, d, e, f                                 ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, a, b, c, d, e, f, g                              ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, a, b, c, d, e, f, g, h                           ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, a, b, c, d, e, f, g, h, i                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (branched: NS17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q] = ???
}

trait Branch6[Ns6[_,_,_,_,_,_], Ns7[_,_,_,_,_,_,_], A, B, C, D, E, F] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns6[A, B, C, D, E, F                                                                       ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns7[A, B, C, D, E, F, a                                                                    ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_8[P8, P9, P9, P10, A, B, C, D, E, F, a, b                                              ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_9[P9, P10, P10, P11, A, B, C, D, E, F, a, b, c                                         ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_10[P10, P11, P11, P12, A, B, C, D, E, F, a, b, c, d                                    ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_11[P11, P12, P12, P13, A, B, C, D, E, F, a, b, c, d, e                                 ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, F, a, b, c, d, e, f                              ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, a, b, c, d, e, f, g                           ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, a, b, c, d, e, f, g, h                        ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (branched: NS16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p] = ???
}

trait Branch7[Ns7[_,_,_,_,_,_,_], Ns8[_,_,_,_,_,_,_,_], A, B, C, D, E, F, G] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns7[A, B, C, D, E, F, G                                                                    ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns8[A, B, C, D, E, F, G, a                                                                 ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_9[P9, P10, P10, P11, A, B, C, D, E, F, G, a, b                                         ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_10[P10, P11, P11, P12, A, B, C, D, E, F, G, a, b, c                                    ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_11[P11, P12, P12, P13, A, B, C, D, E, F, G, a, b, c, d                                 ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, F, G, a, b, c, d, e                              ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, G, a, b, c, d, e, f                           ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, a, b, c, d, e, f, g                        ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h                     ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m, n   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (branched: NS15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o] = ???
}

trait Branch8[Ns8[_,_,_,_,_,_,_,_], Ns9[_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns8[A, B, C, D, E, F, G, H                                                                 ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns9[A, B, C, D, E, F, G, H, a                                                              ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_10[P10, P11, P11, P12, A, B, C, D, E, F, G, H, a, b                                    ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_11[P11, P12, P12, P13, A, B, C, D, E, F, G, H, a, b, c                                 ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, F, G, H, a, b, c, d                              ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, G, H, a, b, c, d, e                           ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, H, a, b, c, d, e, f                        ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g                     ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h                  ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i               ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l, m   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (branched: NS14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, a, b, c, d, e, f, g, h, i, j, k, l, m, n] = ???
}

trait Branch9[Ns9[_,_,_,_,_,_,_,_,_], Ns10[_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns9[A, B, C, D, E, F, G, H, I                                                              ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns10[A, B, C, D, E, F, G, H, I, a                                                          ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_11[P11, P12, P12, P13, A, B, C, D, E, F, G, H, I, a, b                                 ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, F, G, H, I, a, b, c                              ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, G, H, I, a, b, c, d                           ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, H, I, a, b, c, d, e                        ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f                     ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g                  ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h               ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i            ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k, l   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (branched: NS13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, a, b, c, d, e, f, g, h, i, j, k, l, m] = ???
}

trait Branch10[Ns10[_,_,_,_,_,_,_,_,_,_], Ns11[_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns10[A, B, C, D, E, F, G, H, I, J                                                          ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns11[A, B, C, D, E, F, G, H, I, J, a                                                       ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_12[P12, P13, P13, P14, A, B, C, D, E, F, G, H, I, J, a, b                              ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, G, H, I, J, a, b, c                           ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, H, I, J, a, b, c, d                        ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e                     ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f                  ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g               ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h            ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i         ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j, k   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k, l                              ] (branched: NS12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, a, b, c, d, e, f, g, h, i, j, k, l] = ???
}

trait Branch11[Ns11[_,_,_,_,_,_,_,_,_,_,_], Ns12[_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns11[A, B, C, D, E, F, G, H, I, J, K                                                       ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns12[A, B, C, D, E, F, G, H, I, J, K, a                                                    ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_13[P13, P14, P14, P15, A, B, C, D, E, F, G, H, I, J, K, a, b                           ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, H, I, J, K, a, b, c                        ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d                     ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e                  ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f               ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g            ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h         ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i      ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i, j   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j, k                                 ] (branched: NS11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, a, b, c, d, e, f, g, h, i, j, k] = ???
}

trait Branch12[Ns12[_,_,_,_,_,_,_,_,_,_,_,_], Ns13[_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L] extends Branch {
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns13[A, B, C, D, E, F, G, H, I, J, K, L, a                                                 ] = ???
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns12[A, B, C, D, E, F, G, H, I, J, K, L                                                    ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_14[P14, P15, P15, P16, A, B, C, D, E, F, G, H, I, J, K, L, a, b                        ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c                     ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d                  ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e               ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f            ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g         ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h      ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h, i   ] = ???
  def apply[a, b, c, d, e, f, g, h, i, j                                    ] (branched: NS10[a, b, c, d, e, f, g, h, i, j                                    ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, a, b, c, d, e, f, g, h, i, j] = ???
}

trait Branch13[Ns13[_,_,_,_,_,_,_,_,_,_,_,_,_], Ns14[_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns13[A, B, C, D, E, F, G, H, I, J, K, L, M                                                 ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns14[A, B, C, D, E, F, G, H, I, J, K, L, M, a                                              ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_15[P15, P16, P16, P17, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b                     ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c                  ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d               ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e            ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f         ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g      ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g, h   ] = ???
  def apply[a, b, c, d, e, f, g, h, i                                       ] (branched: NS9 [a, b, c, d, e, f, g, h, i                                       ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, a, b, c, d, e, f, g, h, i] = ???
}

trait Branch14[Ns14[_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns15[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns14[A, B, C, D, E, F, G, H, I, J, K, L, M, N                                              ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, a                                           ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_16[P16, P17, P17, P18, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b                  ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c               ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d            ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e         ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f      ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f, g   ] = ???
  def apply[a, b, c, d, e, f, g, h                                          ] (branched: NS8 [a, b, c, d, e, f, g, h                                          ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, a, b, c, d, e, f, g, h] = ???
}

trait Branch15[Ns15[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns16[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O                                           ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a                                        ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_17[P17, P18, P18, P19, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b               ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c            ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d         ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e      ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e, f   ] = ???
  def apply[a, b, c, d, e, f, g                                             ] (branched: NS7 [a, b, c, d, e, f, g                                             ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, a, b, c, d, e, f, g] = ???
}

trait Branch16[Ns16[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns17[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P                                        ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a                                     ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_18[P18, P19, P19, P20, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b            ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c         ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d      ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d, e   ] = ???
  def apply[a, b, c, d, e, f                                                ] (branched: NS6 [a, b, c, d, e, f                                                ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, c, d, e, f] = ???
}

trait Branch17[Ns17[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns18[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q                                     ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a                                  ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_19[P19, P20, P20, P21, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b         ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c      ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c, d   ] = ???
  def apply[a, b, c, d, e                                                   ] (branched: NS5 [a, b, c, d, e                                                   ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, a, b, c, d, e] = ???
}

trait Branch18[Ns18[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns19[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R                                  ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a                               ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_20[P20, P21, P21, P22, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b      ] = ???
  def apply[a, b, c                                                         ] (branched: NS3 [a, b, c                                                         ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b, c   ] = ???
  def apply[a, b, c, d                                                      ] (branched: NS4 [a, b, c, d                                                      ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, a, b, c, d] = ???
}

trait Branch19[Ns19[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns20[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S] extends Branch {
  def apply[dummy                                                           ](branched: NS0[dummy                                                             ]): Ns19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S                               ] = ???
  def apply[a                                                               ](branched: NS1[a                                                                 ]): Ns20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a                            ] = ???
  def apply[a, b                                                            ](branched: NS2[a, b                                                              ]): Out_21[P21, P22, P22, P23, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a, b   ] = ???
  def apply[a, b, c                                                         ](branched: NS3[a, b, c                                                           ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, a, b, c] = ???
}

trait Branch20[Ns20[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns21[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T                            ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, a                         ] = ???
  def apply[a, b                                                            ] (branched: NS2 [a, b                                                            ]): Out_22[P22, P23, P23, P24, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, a, b] = ???
}

trait Branch21[Ns21[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], Ns22[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U                         ] = ???
  def apply[a                                                               ] (branched: NS1 [a                                                               ]): Ns22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, a                      ] = ???
}

trait Branch22[Ns22[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], P23[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_], A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] extends Branch {
  def apply[dummy                                                           ] (branched: NS0 [dummy                                                           ]): Ns22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V                      ] = ???
}
