package molecule.datomic.base.marshalling.sorting

import java.lang.{Double => jDouble, Integer => jInteger, Long => jLong}
import java.math.{BigDecimal => jBigDec, BigInteger => jBigInt}
import java.net.URI
import java.util.{Comparator, Date, UUID, Collection => jCollection, List => jList, Map => jMap}
import clojure.lang.{Keyword, BigInt => clBigInt}
import molecule.core.exceptions.MoleculeException
import molecule.core.marshalling.ast.SortCoordinate


case class SortRows(
  rows: jCollection[jList[AnyRef]],
  sortCoordinates: List[List[SortCoordinate]]
) extends Comparator[jList[AnyRef]] {

  val sortedRows: java.util.ArrayList[jList[AnyRef]] = new java.util.ArrayList(rows)

  def getSorter(sortCoordinate: SortCoordinate): (jList[AnyRef], jList[AnyRef]) => Int = {
    val SortCoordinate(i, asc, attr, opt, tpe, aggrFn, aggrLimit) = sortCoordinate

    def compare(
      x: jList[AnyRef],
      y: jList[AnyRef],
      compareMapValues: (jMap[_, _], jMap[_, _]) => Int
    ): Int = {
      (x.get(i), y.get(i)) match {
        case (null, null)                     => 0
        case (null, _)                        => -1
        case (_, null)                        => 1
        case (m1: jMap[_, _], m2: jMap[_, _]) => compareMapValues(m1, m2)
      }
    }

    if (opt) {
      val mapComparison = tpe match {
        case "String" =>
          (m1: jMap[_, _], m2: jMap[_, _]) =>
            m1.values.iterator.next.asInstanceOf[String].compareTo(m2.values.iterator.next.asInstanceOf[String])

        case "enum" =>
          (m1: jMap[_, _], m2: jMap[_, _]) =>
            m1.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[Keyword].getName.compareTo(
              m2.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[Keyword].getName)

        case "ref" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[jLong].compareTo(
            m2.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[jLong])

        case "Long" | "Int" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[jLong].compareTo(m2.values.iterator.next.asInstanceOf[jLong])

        case "Double" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[jDouble].compareTo(m2.values.iterator.next.asInstanceOf[jDouble])

        case "Boolean" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[Boolean].compareTo(m2.values.iterator.next.asInstanceOf[Boolean])

        case "Date" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[Date].compareTo(m2.values.iterator.next.asInstanceOf[Date])

        case "UUID" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[UUID].compareTo(m2.values.iterator.next.asInstanceOf[UUID])

        case "URI" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[URI].compareTo(m2.values.iterator.next.asInstanceOf[URI])

        case "BigInt" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          (m1.values.iterator.next, m2.values.iterator.next) match {
            case (a: clBigInt, b: clBigInt) => a.toBigInteger.compareTo(b.toBigInteger)
            case (a: jBigInt, b: jBigInt)   => a.compareTo(b)
          }

        case "BigDecimal" => (m1: jMap[_, _], m2: jMap[_, _]) =>
          m1.values.iterator.next.asInstanceOf[jBigDec].compareTo(m2.values.iterator.next.asInstanceOf[jBigDec])

        case "schema" => attr match {
          case "unique$" => (m1: jMap[_, _], m2: jMap[_, _]) =>
            m1.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[Keyword].getName.compareTo(
              m2.values.iterator.next.asInstanceOf[jMap[_, _]].values.iterator.next.asInstanceOf[Keyword].getName)

          case _ => throw MoleculeException(s"Unexpected optional schema attr: $attr")
        }
      }
      if (asc)
        (x: jList[AnyRef], y: jList[AnyRef]) => compare(x, y, mapComparison)
      else
        (x: jList[AnyRef], y: jList[AnyRef]) => compare(y, x, mapComparison)

    } else {

      def compareType: (jList[AnyRef], jList[AnyRef]) => Int = tpe match {
        case "String" | "enum" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[String].compareTo(y.get(i).asInstanceOf[String])

        case "Long" | "ref" | "Int" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[jLong].compareTo(y.get(i).asInstanceOf[jLong])

        case "Double" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[jDouble].compareTo(y.get(i).asInstanceOf[jDouble])

        case "Boolean" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[Boolean].compareTo(y.get(i).asInstanceOf[Boolean])

        case "Date" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[Date].compareTo(y.get(i).asInstanceOf[Date])

        case "UUID" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[UUID].compareTo(y.get(i).asInstanceOf[UUID])

        case "URI" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[URI].compareTo(y.get(i).asInstanceOf[URI])

        case "BigInt" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          (x.get(i), y.get(i)) match {
            case (a: clBigInt, b: clBigInt) => a.toBigInteger.compareTo(b.toBigInteger)
            case (a: jBigInt, b: jBigInt)   => a.compareTo(b)
          }

        case "BigDecimal" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[jBigDec].compareTo(y.get(i).asInstanceOf[jBigDec])

        case "Integer" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).asInstanceOf[jInteger].compareTo(y.get(i).asInstanceOf[jInteger])

        case "Any" => (x: jList[AnyRef], y: jList[AnyRef]) =>
          x.get(i).toString.compareTo(y.get(i).toString)

        case "schema" => attr match {
          case "unique" => (x: jList[AnyRef], y: jList[AnyRef]) =>
            x.get(i).asInstanceOf[String].compareTo(y.get(i).asInstanceOf[String])

          case _ => throw MoleculeException(s"Unexpected mandatory schema attr: $attr")
        }
      }

      val rowComparison = if (aggrFn.isEmpty) {
        compareType
      } else {
        (aggrFn, aggrLimit) match {
          case ("min" | "max" | "distinct" | "rand" | "sample", Some(limit)) => throw MoleculeException(
            s"Unexpectedly trying to sort aggregate with applied limit. Found: $attr($aggrFn($limit)).")

          case ("count" | "count-distinct", _) => (x: jList[AnyRef], y: jList[AnyRef]) =>
            x.get(i).asInstanceOf[jInteger].compareTo(y.get(i).asInstanceOf[jInteger])

          case ("avg" | "stddev" | "variance", _) => (x: jList[AnyRef], y: jList[AnyRef]) =>
            x.get(i).asInstanceOf[jDouble].compareTo(y.get(i).asInstanceOf[jDouble])

          case _ => compareType // min, max, rand, sample, sum, median
        }
      }

      if (asc)
        (x: jList[AnyRef], y: jList[AnyRef]) => rowComparison(x, y)
      else
        (x: jList[AnyRef], y: jList[AnyRef]) => rowComparison(y, x)
    }
  }


  override def compare(x: jList[AnyRef], y: jList[AnyRef]): Int = {
    sorter(x, y)
  }

  def get: jCollection[jList[AnyRef]] = {
    sortedRows.sort(this)
    sortedRows
  }

  // Up to maximum of 7 sub levels (8 including top level) * 5 sort markers per level = 40
  val sorter: (jList[AnyRef], jList[AnyRef]) => Int = {
    val topSorts = sortCoordinates.head
    topSorts.size match {
      case 1 => getSorter(topSorts.head)

      case 2 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          result
        }

      case 3 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          result
        }

      case 4 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          result
        }

      case 5 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          result
        }

      case 6 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        val sort5 = getSorter(topSorts(5))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          result
        }

      case 7 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        val sort5 = getSorter(topSorts(5))
        val sort6 = getSorter(topSorts(6))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          result
        }

      case 8 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        val sort5 = getSorter(topSorts(5))
        val sort6 = getSorter(topSorts(6))
        val sort7 = getSorter(topSorts(7))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          result
        }

      case 9 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        val sort5 = getSorter(topSorts(5))
        val sort6 = getSorter(topSorts(6))
        val sort7 = getSorter(topSorts(7))
        val sort8 = getSorter(topSorts(8))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          result
        }

      case 10 =>
        val sort0 = getSorter(topSorts.head)
        val sort1 = getSorter(topSorts(1))
        val sort2 = getSorter(topSorts(2))
        val sort3 = getSorter(topSorts(3))
        val sort4 = getSorter(topSorts(4))
        val sort5 = getSorter(topSorts(5))
        val sort6 = getSorter(topSorts(6))
        val sort7 = getSorter(topSorts(7))
        val sort8 = getSorter(topSorts(8))
        val sort9 = getSorter(topSorts(9))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          result
        }

      case 11 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          result
        }

      case 12 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          result
        }

      case 13 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          result
        }

      case 14 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          result
        }

      case 15 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          result
        }

      case 16 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          result
        }

      case 17 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          result
        }

      case 18 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          result
        }

      case 19 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          result
        }

      case 20 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          result
        }

      case 21 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          result
        }

      case 22 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          result
        }

      case 23 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          result
        }

      case 24 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          result
        }

      case 25 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          result
        }

      case 26 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          result
        }

      case 27 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          result
        }

      case 28 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          result
        }

      case 29 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          result
        }

      case 30 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          result
        }

      case 31 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          result
        }

      case 32 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          result
        }

      case 33 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          result
        }

      case 34 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          result
        }

      case 35 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          result
        }

      case 36 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        val sort35 = getSorter(topSorts(35))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          if (result == 0) result = sort35(x, y)
          result
        }

      case 37 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        val sort35 = getSorter(topSorts(35))
        val sort36 = getSorter(topSorts(36))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          if (result == 0) result = sort35(x, y)
          if (result == 0) result = sort36(x, y)
          result
        }

      case 38 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        val sort35 = getSorter(topSorts(35))
        val sort36 = getSorter(topSorts(36))
        val sort37 = getSorter(topSorts(37))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          if (result == 0) result = sort35(x, y)
          if (result == 0) result = sort36(x, y)
          if (result == 0) result = sort37(x, y)
          result
        }

      case 39 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        val sort35 = getSorter(topSorts(35))
        val sort36 = getSorter(topSorts(36))
        val sort37 = getSorter(topSorts(37))
        val sort38 = getSorter(topSorts(38))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          if (result == 0) result = sort35(x, y)
          if (result == 0) result = sort36(x, y)
          if (result == 0) result = sort37(x, y)
          if (result == 0) result = sort38(x, y)
          result
        }

      case 40 =>
        val sort0  = getSorter(topSorts.head)
        val sort1  = getSorter(topSorts(1))
        val sort2  = getSorter(topSorts(2))
        val sort3  = getSorter(topSorts(3))
        val sort4  = getSorter(topSorts(4))
        val sort5  = getSorter(topSorts(5))
        val sort6  = getSorter(topSorts(6))
        val sort7  = getSorter(topSorts(7))
        val sort8  = getSorter(topSorts(8))
        val sort9  = getSorter(topSorts(9))
        val sort10 = getSorter(topSorts(10))
        val sort11 = getSorter(topSorts(11))
        val sort12 = getSorter(topSorts(12))
        val sort13 = getSorter(topSorts(13))
        val sort14 = getSorter(topSorts(14))
        val sort15 = getSorter(topSorts(15))
        val sort16 = getSorter(topSorts(16))
        val sort17 = getSorter(topSorts(17))
        val sort18 = getSorter(topSorts(18))
        val sort19 = getSorter(topSorts(19))
        val sort20 = getSorter(topSorts(20))
        val sort21 = getSorter(topSorts(21))
        val sort22 = getSorter(topSorts(22))
        val sort23 = getSorter(topSorts(23))
        val sort24 = getSorter(topSorts(24))
        val sort25 = getSorter(topSorts(25))
        val sort26 = getSorter(topSorts(26))
        val sort27 = getSorter(topSorts(27))
        val sort28 = getSorter(topSorts(28))
        val sort29 = getSorter(topSorts(29))
        val sort30 = getSorter(topSorts(30))
        val sort31 = getSorter(topSorts(31))
        val sort32 = getSorter(topSorts(32))
        val sort33 = getSorter(topSorts(33))
        val sort34 = getSorter(topSorts(34))
        val sort35 = getSorter(topSorts(35))
        val sort36 = getSorter(topSorts(36))
        val sort37 = getSorter(topSorts(37))
        val sort38 = getSorter(topSorts(38))
        val sort39 = getSorter(topSorts(39))
        (x: jList[AnyRef], y: jList[AnyRef]) => {
          var result = sort0(x, y)
          if (result == 0) result = sort1(x, y)
          if (result == 0) result = sort2(x, y)
          if (result == 0) result = sort3(x, y)
          if (result == 0) result = sort4(x, y)
          if (result == 0) result = sort5(x, y)
          if (result == 0) result = sort6(x, y)
          if (result == 0) result = sort7(x, y)
          if (result == 0) result = sort8(x, y)
          if (result == 0) result = sort9(x, y)
          if (result == 0) result = sort10(x, y)
          if (result == 0) result = sort11(x, y)
          if (result == 0) result = sort12(x, y)
          if (result == 0) result = sort13(x, y)
          if (result == 0) result = sort14(x, y)
          if (result == 0) result = sort15(x, y)
          if (result == 0) result = sort16(x, y)
          if (result == 0) result = sort17(x, y)
          if (result == 0) result = sort18(x, y)
          if (result == 0) result = sort19(x, y)
          if (result == 0) result = sort20(x, y)
          if (result == 0) result = sort21(x, y)
          if (result == 0) result = sort22(x, y)
          if (result == 0) result = sort23(x, y)
          if (result == 0) result = sort24(x, y)
          if (result == 0) result = sort25(x, y)
          if (result == 0) result = sort26(x, y)
          if (result == 0) result = sort27(x, y)
          if (result == 0) result = sort28(x, y)
          if (result == 0) result = sort29(x, y)
          if (result == 0) result = sort30(x, y)
          if (result == 0) result = sort31(x, y)
          if (result == 0) result = sort32(x, y)
          if (result == 0) result = sort33(x, y)
          if (result == 0) result = sort34(x, y)
          if (result == 0) result = sort35(x, y)
          if (result == 0) result = sort36(x, y)
          if (result == 0) result = sort37(x, y)
          if (result == 0) result = sort38(x, y)
          if (result == 0) result = sort39(x, y)
          result
        }
    }
  }
}

