package molecule.core.expression

import molecule.core.api.Keywords

/** Apply methods of arity 1-22 taking aggregate keywords. */

trait AggregateApi[NsT, NsList, NsInt, NsDouble] {
  def apply(v: Keywords.min)   : NsT = ???
  def apply(v: Keywords.max)   : NsT = ???
  def apply(v: Keywords.rand)  : NsT = ???
  def apply(v: Keywords.sample): NsT = ???
  def apply(v: Keywords.sum)   : NsT = ???
  def apply(v: Keywords.median): NsT = ???

  def apply(v: Keywords.mins)    : NsList = ???
  def apply(v: Keywords.maxs)    : NsList = ???
  def apply(v: Keywords.distinct): NsList = ???
  def apply(v: Keywords.rands)   : NsList = ???
  def apply(v: Keywords.samples) : NsList = ???

  def apply(v: Keywords.count)        : NsInt = ???
  def apply(v: Keywords.countDistinct): NsInt = ???

  def apply(v: Keywords.avg)     : NsDouble = ???
  def apply(v: Keywords.variance): NsDouble = ???
  def apply(v: Keywords.stddev)  : NsDouble = ???
}

trait Aggr_00_L0[a[_],b                                                 ,Ns[q[_],_                                                 ]] extends AggregateApi[Ns[a,b                            ], Ns[a,b                            ], Ns[a,b                            ], Ns[a,b                            ]]
trait Aggr_00_L1[a[_],b,c[_],d                                          ,Ns[q[_],_,r[_],_                                          ]] extends AggregateApi[Ns[a,b,c,d                        ], Ns[a,b,c,d                        ], Ns[a,b,c,d                        ], Ns[a,b,c,d                        ]]
trait Aggr_00_L2[a[_],b,c[_],d,e[_],f                                   ,Ns[q[_],_,r[_],_,s[_],_                                   ]] extends AggregateApi[Ns[a,b,c,d,e,f                    ], Ns[a,b,c,d,e,f                    ], Ns[a,b,c,d,e,f                    ], Ns[a,b,c,d,e,f                    ]]
trait Aggr_00_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ], Ns[a,b,c,d,e,f,g,h                ], Ns[a,b,c,d,e,f,g,h                ], Ns[a,b,c,d,e,f,g,h                ]]
trait Aggr_00_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ], Ns[a,b,c,d,e,f,g,h,i,j            ], Ns[a,b,c,d,e,f,g,h,i,j            ], Ns[a,b,c,d,e,f,g,h,i,j            ]]
trait Aggr_00_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ]]
trait Aggr_00_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ]]
trait Aggr_00_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p]]

trait Aggr_01_L0[a[_],b                                                 ,A,Ns[q[_],_                                                 ,_]] extends AggregateApi[Ns[a,b                            ,A], Ns[a,b                            , List[A]], Ns[a,b                            , Int], Ns[a,b                            , Double]]
trait Aggr_01_L1[a[_],b,c[_],d                                          ,A,Ns[q[_],_,r[_],_                                          ,_]] extends AggregateApi[Ns[a,b,c,d                        ,A], Ns[a,b,c,d                        , List[A]], Ns[a,b,c,d                        , Int], Ns[a,b,c,d                        , Double]]
trait Aggr_01_L2[a[_],b,c[_],d,e[_],f                                   ,A,Ns[q[_],_,r[_],_,s[_],_                                   ,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A], Ns[a,b,c,d,e,f                    , List[A]], Ns[a,b,c,d,e,f                    , Int], Ns[a,b,c,d,e,f                    , Double]]
trait Aggr_01_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A], Ns[a,b,c,d,e,f,g,h                , List[A]], Ns[a,b,c,d,e,f,g,h                , Int], Ns[a,b,c,d,e,f,g,h                , Double]]
trait Aggr_01_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A], Ns[a,b,c,d,e,f,g,h,i,j            , List[A]], Ns[a,b,c,d,e,f,g,h,i,j            , Int], Ns[a,b,c,d,e,f,g,h,i,j            , Double]]
trait Aggr_01_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A], Ns[a,b,c,d,e,f,g,h,i,j,k,l        , List[A]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        , Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        , Double]]
trait Aggr_01_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    , List[A]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    , Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    , Double]]
trait Aggr_01_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p, List[A]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p, Double]]

trait Aggr_02_L0[a[_],b                                                 ,A,B,Ns[q[_],_                                                 ,_,_]] extends AggregateApi[Ns[a,b                            ,A,B], Ns[a,b                            ,A, List[B]], Ns[a,b                            ,A, Int], Ns[a,b                            ,A, Double]]
trait Aggr_02_L1[a[_],b,c[_],d                                          ,A,B,Ns[q[_],_,r[_],_                                          ,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B], Ns[a,b,c,d                        ,A, List[B]], Ns[a,b,c,d                        ,A, Int], Ns[a,b,c,d                        ,A, Double]]
trait Aggr_02_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B], Ns[a,b,c,d,e,f                    ,A, List[B]], Ns[a,b,c,d,e,f                    ,A, Int], Ns[a,b,c,d,e,f                    ,A, Double]]
trait Aggr_02_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B], Ns[a,b,c,d,e,f,g,h                ,A, List[B]], Ns[a,b,c,d,e,f,g,h                ,A, Int], Ns[a,b,c,d,e,f,g,h                ,A, Double]]
trait Aggr_02_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B], Ns[a,b,c,d,e,f,g,h,i,j            ,A, List[B]], Ns[a,b,c,d,e,f,g,h,i,j            ,A, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A, Double]]
trait Aggr_02_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A, List[B]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A, Double]]
trait Aggr_02_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A, List[B]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A, Double]]
trait Aggr_02_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A, List[B]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A, Double]]

trait Aggr_03_L0[a[_],b                                                 ,A,B,C,Ns[q[_],_                                                 ,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C], Ns[a,b                            ,A,B, List[C]], Ns[a,b                            ,A,B, Int], Ns[a,b                            ,A,B, Double]]
trait Aggr_03_L1[a[_],b,c[_],d                                          ,A,B,C,Ns[q[_],_,r[_],_                                          ,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C], Ns[a,b,c,d                        ,A,B, List[C]], Ns[a,b,c,d                        ,A,B, Int], Ns[a,b,c,d                        ,A,B, Double]]
trait Aggr_03_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C], Ns[a,b,c,d,e,f                    ,A,B, List[C]], Ns[a,b,c,d,e,f                    ,A,B, Int], Ns[a,b,c,d,e,f                    ,A,B, Double]]
trait Aggr_03_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C], Ns[a,b,c,d,e,f,g,h                ,A,B, List[C]], Ns[a,b,c,d,e,f,g,h                ,A,B, Int], Ns[a,b,c,d,e,f,g,h                ,A,B, Double]]
trait Aggr_03_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B, List[C]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B, Double]]
trait Aggr_03_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B, List[C]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B, Double]]
trait Aggr_03_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B, List[C]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B, Double]]
trait Aggr_03_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B, List[C]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B, Double]]

trait Aggr_04_L0[a[_],b                                                 ,A,B,C,D,Ns[q[_],_                                                 ,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D], Ns[a,b                            ,A,B,C, List[D]], Ns[a,b                            ,A,B,C, Int], Ns[a,b                            ,A,B,C, Double]]
trait Aggr_04_L1[a[_],b,c[_],d                                          ,A,B,C,D,Ns[q[_],_,r[_],_                                          ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D], Ns[a,b,c,d                        ,A,B,C, List[D]], Ns[a,b,c,d                        ,A,B,C, Int], Ns[a,b,c,d                        ,A,B,C, Double]]
trait Aggr_04_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D], Ns[a,b,c,d,e,f                    ,A,B,C, List[D]], Ns[a,b,c,d,e,f                    ,A,B,C, Int], Ns[a,b,c,d,e,f                    ,A,B,C, Double]]
trait Aggr_04_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D], Ns[a,b,c,d,e,f,g,h                ,A,B,C, List[D]], Ns[a,b,c,d,e,f,g,h                ,A,B,C, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C, Double]]
trait Aggr_04_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C, List[D]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C, Double]]
trait Aggr_04_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C, List[D]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C, Double]]
trait Aggr_04_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C, List[D]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C, Double]]
trait Aggr_04_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C, List[D]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C, Double]]

trait Aggr_05_L0[a[_],b                                                 ,A,B,C,D,E,Ns[q[_],_                                                 ,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E], Ns[a,b                            ,A,B,C,D, List[E]], Ns[a,b                            ,A,B,C,D, Int], Ns[a,b                            ,A,B,C,D, Double]]
trait Aggr_05_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E], Ns[a,b,c,d                        ,A,B,C,D, List[E]], Ns[a,b,c,d                        ,A,B,C,D, Int], Ns[a,b,c,d                        ,A,B,C,D, Double]]
trait Aggr_05_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E], Ns[a,b,c,d,e,f                    ,A,B,C,D, List[E]], Ns[a,b,c,d,e,f                    ,A,B,C,D, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D, Double]]
trait Aggr_05_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D, List[E]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D, Double]]
trait Aggr_05_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D, List[E]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D, Double]]
trait Aggr_05_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D, List[E]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D, Double]]
trait Aggr_05_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D, List[E]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D, Double]]
trait Aggr_05_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D, List[E]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D, Double]]

trait Aggr_06_L0[a[_],b                                                 ,A,B,C,D,E,F,Ns[q[_],_                                                 ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F], Ns[a,b                            ,A,B,C,D,E, List[F]], Ns[a,b                            ,A,B,C,D,E, Int], Ns[a,b                            ,A,B,C,D,E, Double]]
trait Aggr_06_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F], Ns[a,b,c,d                        ,A,B,C,D,E, List[F]], Ns[a,b,c,d                        ,A,B,C,D,E, Int], Ns[a,b,c,d                        ,A,B,C,D,E, Double]]
trait Aggr_06_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F], Ns[a,b,c,d,e,f                    ,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E, Double]]
trait Aggr_06_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E, Double]]
trait Aggr_06_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E, Double]]
trait Aggr_06_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E, Double]]
trait Aggr_06_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E, Double]]
trait Aggr_06_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E, List[F]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E, Double]]

trait Aggr_07_L0[a[_],b                                                 ,A,B,C,D,E,F,G,Ns[q[_],_                                                 ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G], Ns[a,b                            ,A,B,C,D,E,F, List[G]], Ns[a,b                            ,A,B,C,D,E,F, Int], Ns[a,b                            ,A,B,C,D,E,F, Double]]
trait Aggr_07_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G], Ns[a,b,c,d                        ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d                        ,A,B,C,D,E,F, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F, Double]]
trait Aggr_07_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F, Double]]
trait Aggr_07_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F, Double]]
trait Aggr_07_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F, Double]]
trait Aggr_07_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F, Double]]
trait Aggr_07_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F, Double]]
trait Aggr_07_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F, List[G]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F, Double]]

trait Aggr_08_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H], Ns[a,b                            ,A,B,C,D,E,F,G, List[H]], Ns[a,b                            ,A,B,C,D,E,F,G, Int], Ns[a,b                            ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H], Ns[a,b,c,d                        ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G, Double]]
trait Aggr_08_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G, List[H]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G, Double]]

trait Aggr_09_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I], Ns[a,b                            ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b                            ,A,B,C,D,E,F,G,H, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H, Double]]
trait Aggr_09_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H, List[I]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H, Double]]

trait Aggr_10_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J], Ns[a,b                            ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I, Double]]
trait Aggr_10_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I, List[J]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I, Double]]

trait Aggr_11_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J, Double]]
trait Aggr_11_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J, List[K]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J, Double]]

trait Aggr_12_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K, Double]]
trait Aggr_12_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K, List[L]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K, Double]]

trait Aggr_13_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L, Double]]
trait Aggr_13_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L, List[M]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L, Double]]

trait Aggr_14_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]
trait Aggr_14_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M, List[N]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M, Double]]

trait Aggr_15_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]
trait Aggr_15_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N, List[O]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N, Double]]

trait Aggr_16_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]
trait Aggr_16_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, List[P]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O, Double]]

trait Aggr_17_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]
trait Aggr_17_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, List[Q]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, Double]]

trait Aggr_18_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]
trait Aggr_18_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, List[R]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q, Double]]

trait Aggr_19_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]
trait Aggr_19_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, List[S]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R, Double]]

trait Aggr_20_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]
trait Aggr_20_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, List[T]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S, Double]]

trait Aggr_21_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]
trait Aggr_21_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, List[U]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T, Double]]

trait Aggr_22_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]
trait Aggr_22_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, List[V]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U, Double]]

trait Aggr_23_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]
trait Aggr_23_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, List[W]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V, Double]]

trait Aggr_24_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]
trait Aggr_24_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, List[X]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, Double]]

trait Aggr_25_L0[a[_],b                                                 ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_                                                 ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L1[a[_],b,c[_],d                                          ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_                                          ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d                        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L2[a[_],b,c[_],d,e[_],f                                   ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_                                   ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f                    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L3[a[_],b,c[_],d,e[_],f,g[_],h                            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_,t[_],_                            ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f,g,h                ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L4[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j                     ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_                     ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f,g,h,i,j            ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L5[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l              ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_              ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l        ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L6[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n       ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_       ,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n    ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
trait Aggr_25_L7[a[_],b,c[_],d,e[_],f,g[_],h,i[_],j,k[_],l,m[_],n,o[_],p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Ns[q[_],_,r[_],_,s[_],_,t[_],_,u[_],_,v[_],_,w[_],_,x[_],_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]] extends AggregateApi[Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, List[Y]], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Int], Ns[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X, Double]]
